### ISSUE TITLE
[BUG] Inconsistent sprite scaling on character customization page

### ISSUE THREAD

**Issue by Recoherent** [shiptest-ss13/Shiptest#1004]
## Round ID:
`825`, but happens relatively consistently on multiple rounds

## Testmerges:
Revision: `096c8f37e7c5760a9f30d617b558bc89c03416ba`

## Reproduction:
Character customization (notably on IPCs) occasionally, somewhat randomly adds an additional layer of vertical pixel to the character visualizer. The actual layer that is duplicated is inconsistent. I am not certain if this is related to why one of my statics is consistently a pixel shorter than other IPCs when in-game; assuming that is a separate issue.
![image](https://user-images.githubusercontent.com/10237657/165662603-f823a869-3d13-4322-ac46-92681758b8f7.png)

**Comment by Fikou** [comment]
seems to be a byond issue, not sure if we can do anything 'bout it?
