### ISSUE TITLE
[BUG] Wright Class Bathroom prone to vanishing.

### ISSUE THREAD

**Issue by AsciiSquid** [shiptest-ss13/Shiptest#1026]
## Round ID: [838](https://shiptest.ga/stats/rounds/838)

Especially annoying since most of doors on wright are wood, so this pretty much decompresses the whole ship.

## Testmerges: 
[#726: 'KapuLimbs v1.1: Update Icons Soft Refactor & Clockvox' by Kapu1178 at commit 3c929fea1d](https://github.com/Shiptest-SS13/Shiptest/pull/726)
[#652: 'Weathers' by Azarak at commit 56ae296e66](https://github.com/Shiptest-SS13/Shiptest/pull/652)
[#928: 'Resprites intercoms' by Quantum-M at commit cdc97c5111](https://github.com/Shiptest-SS13/Shiptest/pull/928)
[#943: 'Bay clicky noises 3: Zzzzzip' by retlaw34 at commit 44acf821f3](https://github.com/Shiptest-SS13/Shiptest/pull/943)
[#950: 'Adds cement and concrete, used to make concrete walls and floors.' by tmtmtl30 at commit 36c1221bcf](https://github.com/Shiptest-SS13/Shiptest/pull/950)
[#1005: 'Ports MC initialization refactor' by Vexylius at commit 2b701e03e7](https://github.com/Shiptest-SS13/Shiptest/pull/1005)
[#902: 'New ruin any percent' by SweetBlueSylveon at commit 16777c0e3b](https://github.com/Shiptest-SS13/Shiptest/pull/902)
[#872: 'Turf fire' by retlaw34 at commit 489c1aad31](https://github.com/Shiptest-SS13/Shiptest/pull/872)
[#601: 'Overmap Expansion #3' by retlaw34 at commit 4a389c13ab](https://github.com/Shiptest-SS13/Shiptest/pull/601)
[#132: 'Readds Explosive Decompression' by MarkSuckerberg at commit 66b69f88fc](https://github.com/Shiptest-SS13/Shiptest/pull/132)

## Reproduction:
+ Get a Wright Class ship.
+ Land it in space/signal ruin.
+ ???
+ ![image](https://user-images.githubusercontent.com/39249137/166805733-a7c17142-2573-4c01-9efa-8847994cc2d1.png)

**Comment by PrefabQuasar** [comment]
thats not it dissapearing i think, thats datum mats floor tiles back at it again
the plastic tiles are datum mat ones, which always replace their icon with whatever they land on for SOME GODDAMN REASON
