### ISSUE TITLE
[BUG]Box class has no lights

### ISSUE THREAD

**Issue by ToasterBan** [shiptest-ss13/Shiptest#1063]
## Testmerges:
 #726: 'KapuLimbs v1.1: Update Icons Soft Refactor & Clockvox' by Kapu1178 at commit f985cd0852
#652: 'Weathers' by Azarak at commit 56ae296e66
#928: 'Resprites intercoms' by Quantum-M at commit cdc97c5111
#943: 'Bay clicky noises 3: Zzzzzip' by retlaw34 at commit 44acf821f3
#950: 'Adds cement and concrete, used to make concrete walls and floors.' by tmtmtl30 at commit 36c1221bcf
#902: 'New ruin any percent' by SweetBlueSylveon at commit 16777c0e3b
#872: 'Turf fire' by retlaw34 at commit 64f29a733e
#601: 'Overmap Expansion #3' by retlaw34 at commit a731c83965
#132: 'Readds Explosive Decompression' by MarkSuckerberg at commit 66b69f88fc
#945: 'The MedTechtm chemical manufacturing plant ruin ' by disappointedButNotSuprised at commit 168f8d8a5c
#1001: '[DNM] Adds the options for IPCs to have their brains as MMI's' by Bokkiewokkie at commit 41977ef658
#1056: 'Gun DealerShip - An Admin-Only Event Ship' by coleminerman at commit e69e277949
#1050: 'Adds the Scav-class Drifter' by someguyjust at commit 4c524544c3
#1036: 'The Carina RP Update' by Apogee-dev at commit 7ed4cff9c9
#1043: 'Boyardee updates 2' by bluezorua at commit 8cb558ec1a

**Comment by Sylphily** [comment]
This is not a bug this is intended
