### ISSUE TITLE
[BUG] Rolling Jumpsuits Is Just Seven Layers Of Fucked

### ISSUE THREAD

**Issue by tiramisuapimancer** [shiptest-ss13/Shiptest#1076]
## Round ID:
im localhosting

## Testmerges:
no

## Reproduction:
Alt click an adjustable suit item as a plantigrade, notice that it does jack shit fuck all to its actual sprite despite the description claiming that you are or are not wearing it casually.

Alt click an adjustable suit item as a digitigrade and watch as it starts actually fitting you, but only when it's set to be worn casually.

![image](https://user-images.githubusercontent.com/32314478/168479941-e4e18642-cc4e-4b10-976d-eeda14747384.png)
Both of these jumpsuits are being "worn casually", which USED to make them awesome rolled down chell portal 2 dripstyle but now does either nothing or makes them fit but not casually so.

**Comment by tiramisuapimancer** [comment]
New information: attempting to roll a jumpsuit that doesn't have a digitigrade variation instead toggles the application of the female spritecut system where a few pixels are removed from the jumpsuit's sprite so that it Looks Like It Has Tits or something. This only works if the mob wearing it is actually female. The casual state will be the version of the sprite that doesn't have the pixels cut.

Attempting to roll a jumpsuit that has no digitigrade variations as a male digitigrade does absolutely nothing at all

**Comment by tiramisuapimancer** [comment]
Further information I figure might be useful: VV shows that the actual adjusted var of the suit is still considered ALT_STYLE. Just it's not getting the icons right for some reason.

**Comment by Sylphily** [comment]
Bruh wtf, this is some funky ass shit man!

**Comment by Zevotech** [comment]
we left the shitcode unchecked for too long and it has MUTATED

**Comment by tiramisuapimancer** [comment]
the code equivalent of prion disease

**Comment by triplezeta** [comment]
![image](https://user-images.githubusercontent.com/51932018/168735403-8ebc26e6-7a0a-4e8c-9f6d-574a31db7319.png)


any clothing item that has `fitted = FEMALE_UNIFORM_TOP` adjusts properly for female characters. However, since the vast majority of clothing items that have this set are skirts, it is mostly pointless

**Comment by tiramisuapimancer** [comment]
I have updated the title of the issue to better reflect these developments.
