### ISSUE TITLE
[BUG] IPCs have lungs

### ISSUE THREAD

**Issue by rye-rice** [shiptest-ss13/Shiptest#112]
## Reproduction:
IPCs spawn with lungs. They are completly useless and spam a message if decayed.
A easy way to see this is to do self surgery organ manip on chest
![image](https://user-images.githubusercontent.com/58402542/127850967-c92b6fe7-6f64-4ee9-8f5c-827f76553a57.png)
another way is to health analyze a dead ipc to see the damaged lungs show up
![image](https://user-images.githubusercontent.com/58402542/127851676-3ced75a6-0f28-4c5f-9cb6-a5f64c68f91e.png)

**Comment by tiramisuapimancer** [comment]
they're for collecting change
