### ISSUE TITLE
[BUG] Dwayne-Class External Room is missing an APC.

### ISSUE THREAD

**Issue by Onule** [shiptest-ss13/Shiptest#1131]
## Reproduction:

![imagem](https://user-images.githubusercontent.com/4581352/170832032-5c6165cf-aaf9-4b93-a605-2bb20e71859b.png)

The external room is lacking an APC. The blast doors there are powered by magic, and you need to place down an APC to actually depower them, thought that might be a bug itself (trying to crowbar the airlock electronics out causes them to close, if they're still powered.).

**Comment by Zevotech** [comment]
huh, never thought about it that way.
