### ISSUE TITLE
[minor bug] Reinforced thindows do not count as airtight

### ISSUE THREAD

**Issue by Yellow-Mushroom** [shiptest-ss13/Shiptest#1172]
Issue reported from  Round ID: 909 (Shiptest)

Reporting client version: 514.1583

When using a ship that has thindows, you cannot redeclare areas that are closed inside those thindows as its not "air tight". 

Replacing end thindow pieces with walls does not work.

This disallows area remapping:
![image](https://user-images.githubusercontent.com/75814831/172041529-818a5319-efab-4211-949a-b9a992257c3e.png)

This also disallows area remapping:
![image](https://user-images.githubusercontent.com/75814831/172041545-02f951d9-dcb7-45dc-8e74-992e948db3c0.png)

This allows area remapping, showing its not just the thindoor causing this issue:
![image](https://user-images.githubusercontent.com/75814831/172041568-60e835b9-fcc2-4884-a958-2a0bb8ebeb2e.png)

This could pose further issue than pill classes. as a ship a ship I've been seeing passed around in #shipyard  has a thindow enclosed area, and re-area'ing could mess it up.

**Comment by Yellow-Mushroom** [comment]
Someone in the discord corrected me, the minimum area for expansion is 3x3, so my 1x3 expansion failed due to that, not thindows.

**Comment by Yellow-Mushroom** [comment]
Thindows could still possibly pose an issue with area remapping, but I havent tested it yet with a 3x3 and it is late. I will re-open if that is the case

**Comment by Sylphily** [comment]
huh the more i know
