### ISSUE TITLE
[BUG] GPSes are just completely fucked

### ISSUE THREAD

**Issue by AtlasRules** [shiptest-ss13/Shiptest#1200]
## Testmerges: [#132: 'Readds Explosive Decompression' by MarkSuckerberg at commit 715c79f1bd](https://github.com/Shiptest-SS13/Shiptest/pull/132)
[#928: 'Resprites intercoms' by Quantum-M at commit df55170366](https://github.com/Shiptest-SS13/Shiptest/pull/928)
[#1159: 'Lagoon-class Cruise Ship' by TypeVar at commit 0cd10184be](https://github.com/Shiptest-SS13/Shiptest/pull/1159)
[#1173: 'adds limus class ship' by Ketrai at commit 650ac0b454](https://github.com/Shiptest-SS13/Shiptest/pull/1173)
[#1182: 'basic outposts and missions, v0.1' by tmtmtl30 at commit 633a857ddc](https://github.com/Shiptest-SS13/Shiptest/pull/1182)
[#950: 'Adds cement and concrete, used to make concrete walls and floors.' by tmtmtl30 at commit 0d8e9b4a89](https://github.com/Shiptest-SS13/Shiptest/pull/950)
[#1001: 'Adds the options for IPCs to have their brains as MMI's' by Bokkiewokkie at commit fceddc5a1a](https://github.com/Shiptest-SS13/Shiptest/pull/1001)
[#1007: 'Keppification' by MarkSuckerberg at commit c6ae64982a](https://github.com/Shiptest-SS13/Shiptest/pull/1007)
[#1058: '[TM-ONLY] Revert "speech controllers and hearers_in_view improvements"' by ZephyrTFA at commit ff8e5562a3](https://github.com/Shiptest-SS13/Shiptest/pull/1058)
[#1067: 'Research Interim: Redemption: Director's Cut' by triplezeta at commit 5f884ae0cd](https://github.com/Shiptest-SS13/Shiptest/pull/1067)
[#1141: 'Syndicate Cascade Class Genetics Vessel' by spockye at commit 44926b2722](https://github.com/Shiptest-SS13/Shiptest/pull/1141)
[#1161: 'Adds the Tranquility-class Flying Apartment Complex' by PrefabQuasar at commit b990726590](https://github.com/Shiptest-SS13/Shiptest/pull/1161)
[#1165: 'Fixes rnd servers not initializing correctly on map load' by IndusRobot at commit 29a1031dc5](https://github.com/Shiptest-SS13/Shiptest/pull/1165)
[#1166: 'Fixes unpowered holopads bricking calling holopads' by IndusRobot at commit 39e85992ce](https://github.com/Shiptest-SS13/Shiptest/pull/1166)
[#1174: 'Ports TG ambience' by retlaw34 at commit d428e76e95](https://github.com/Shiptest-SS13/Shiptest/pull/1174)
[#1183: 'optimizes icon2html() for icon files known to be in the rsc at compile time' by triplezeta at commit f4ba983dca](https://github.com/Shiptest-SS13/Shiptest/pull/1183)
[#1019: 'Adds unique ship access, and updates card modification programs to manage your ship access' by IndusRobot at commit c01f665507](https://github.com/Shiptest-SS13/Shiptest/pull/1019)
[#1079: 'Welding animation port' by Vexylius at commit c3af6aa9f3](https://github.com/Shiptest-SS13/Shiptest/pull/1079)
[#1195: 'Port borg module selection radial menu' by dragomagol at commit 3dc80ead3b](https://github.com/Shiptest-SS13/Shiptest/pull/1195)
[#1193: 'Resprites the IPC/pAI recharge cable!' by Imaginos16 at commit 18aa19e0eb](https://github.com/Shiptest-SS13/Shiptest/pull/1193)
[#1149: '(Hopefully) Final jungle ruin adjustments and remaps' by Zevotech at commit d08546fe85](https://github.com/Shiptest-SS13/Shiptest/pull/1149)
[#1119: 'A ship ton of engineering resprites' by retlaw34 at commit da1b720116](https://github.com/Shiptest-SS13/Shiptest/pull/1119)

## Reproduction: 1. Get a GPS, either by making one or spawning on a ship with one.
2. Try to use it.
3. See that it's completely fucked.

**Comment by Imaginos16** [comment]
Screenshot of the error

![image](https://user-images.githubusercontent.com/77556824/177639966-5bce5396-d01d-43ef-8bea-45433b857897.png)

**Comment by AtlasRules** [comment]
ty ty
