### ISSUE TITLE
[BUG] Space pod Bugs (Cargo, Weapons, Internal Atmos)

### ISSUE THREAD

**Issue by Derpguy3** [shiptest-ss13/Shiptest#1258]
Issue reported from  Round ID: [954](https://shiptest.ga/stats/rounds/954) (Shiptest)

Reporting client version: 514.1582

**Test Merges**
[#132: 'Readds Explosive Decompression' by MarkSuckerberg at commit f1168c3c9d](https://github.com/Shiptest-SS13/Shiptest/pull/132)
[#950: 'Adds cement and concrete, used to make concrete walls and floors.' by tmtmtl30 at commit c42d26c21d](https://github.com/Shiptest-SS13/Shiptest/pull/950)
[#1141: 'Syndicate Cascade Class Genetics Vessel' by spockye at commit 8d6a829485](https://github.com/Shiptest-SS13/Shiptest/pull/1141)
[#1149: '(Hopefully) Final jungle ruin adjustments and remaps' by Zevotech at commit 1624b2204f](https://github.com/Shiptest-SS13/Shiptest/pull/1149)
[#1159: 'Lagoon-class Cruise Ship' by TypeVar at commit 0cd10184be](https://github.com/Shiptest-SS13/Shiptest/pull/1159)
[#1173: 'adds limus class ship' by Ketrai at commit 054301eb0b](https://github.com/Shiptest-SS13/Shiptest/pull/1173)
[#1182: 'basic outposts and missions, v0.1' by tmtmtl30 at commit 98586c893b](https://github.com/Shiptest-SS13/Shiptest/pull/1182)
[#1079: 'Welding animation port' by Vexylius at commit 6387e35247](https://github.com/Shiptest-SS13/Shiptest/pull/1079)
[#1067: 'Research Interim: Redemption: Director's Cut' by triplezeta at commit a429572e09](https://github.com/Shiptest-SS13/Shiptest/pull/1067)
[#1235: 'Another Rube Goldpatch' by SweetBlueSylveon at commit 11b76d30a4](https://github.com/Shiptest-SS13/Shiptest/pull/1235)
[#1216: 'Adds a new jungle ruin, 'Old Crashed Interceptor'' by Yellow-Mushroom at commit 8958c161c1](https://github.com/Shiptest-SS13/Shiptest/pull/1216)
[#1170: 'Nerfs the oldcode nukie ship map for being a deathtrap.' by Zevotech at commit 7553f9c3de](https://github.com/Shiptest-SS13/Shiptest/pull/1170)
[#1237: 'overmap star refactor' by tmtmtl30 at commit b3b75d75aa](https://github.com/Shiptest-SS13/Shiptest/pull/1237)
[#1128: 'Pubby class remake' by spockye at commit 392df6ed08](https://github.com/Shiptest-SS13/Shiptest/pull/1128)
[#1213: 'The Trinea' by someguyjust at commit 85a83e19bd](https://github.com/Shiptest-SS13/Shiptest/pull/1213)
[#1203: 'Nemo-Class RnD & Medbay Tweaks' by TypeVar at commit ac05e0293b](https://github.com/Shiptest-SS13/Shiptest/pull/1203)
[#1206: 'Rebalances Xenobio aspects' by Ketrai at commit 13a869c175](https://github.com/Shiptest-SS13/Shiptest/pull/1206)

**Issue Description**
Space pods seem to be unable to unload cargo that is put inside of it (I had used the ore storage module) causing whatever you put inside of the pod to become stuck.
When firing weapons/mining equipment the space pods tend to shoot themselves either when moving and flying into their own shots or even occasionally while not moving or at extremely slow speeds, leading to unideal situations.
In addition, when using an air canister for pod internals, it shows a "too much oxygen" warning and begins to suffocate your character. I had used a preloaded canister which had a 21% Oxygen/79% Nitrogen ratio.

**Issue Reproduction**
- Space Pod Cargo
1. Install a cargo module into a space pod (I used an ore storage module in this case)
2. Insert the associated cargo, optionally filling them with something. (Crate for crates, Ore box for ore storage)
3. Attempt to unload the cargo using the button in the space pod tab.
4. Receive nothing in return, along with no feedback.

- Space Pod Weapons/Mining Equipment
1. Install a weapon or mining equipment on the space pod.
2. Fly around and fire your equipment.
2.1. Sit still or fly at extremely slow speeds and fire your equipment.
2.2. Rotate the pod around and fire your equipment.
3. Occasionally shoot your own pod.

- Space Pod Internals
1. Use a pod with a preloaded air canister OR build and insert a premixed air canister.
2. Get inside the pod
3. A "Too much oxygen" warning will appear and your character will begin suffocating without equipped internals.

**Comment by ZephyrTFA** [comment]
Space Pods are deprecated and the only reason they have not been fully removed as of yet is because no one wants to take the time to do so

**Comment by rye-rice** [comment]
there was a pr that removed them, but it went stale
