### ISSUE TITLE
[BUG] Survivor suit lacks hood object icon

### ISSUE THREAD

**Issue by Derpguy3** [shiptest-ss13/Shiptest#1275]
Issue reported from  Round ID: [967](https://shiptest.ga/stats/rounds/967) (Shiptest)

Reporting client version: 514.1582

**Test Merges**
[#950: 'Adds cement and concrete, used to make concrete walls and floors.' by tmtmtl30 at commit c42d26c21d](https://github.com/Shiptest-SS13/Shiptest/pull/950)
[#1141: 'Syndicate Cascade Class Genetics Vessel' by spockye at commit 93289b7483](https://github.com/Shiptest-SS13/Shiptest/pull/1141)
[#1159: 'Lagoon-class Cruise Ship' by TypeVar at commit 1ab4d598b8](https://github.com/Shiptest-SS13/Shiptest/pull/1159)
[#1173: 'adds limus class ship' by Ketrai at commit d6d9a4c950](https://github.com/Shiptest-SS13/Shiptest/pull/1173)
[#1182: 'basic outposts and missions, v0.1' by tmtmtl30 at commit 98586c893b](https://github.com/Shiptest-SS13/Shiptest/pull/1182)
[#1067: 'Research Interim: Redemption: Director's Cut' by triplezeta at commit a429572e09](https://github.com/Shiptest-SS13/Shiptest/pull/1067)
[#1216: 'Adds a new jungle ruin, 'Old Crashed Interceptor'' by Yellow-Mushroom at commit 8958c161c1](https://github.com/Shiptest-SS13/Shiptest/pull/1216)
[#1170: 'Nerfs the oldcode nukie ship map for being a deathtrap.' by Zevotech at commit 7553f9c3de](https://github.com/Shiptest-SS13/Shiptest/pull/1170)
[#1237: 'overmap star refactor' by tmtmtl30 at commit b3b75d75aa](https://github.com/Shiptest-SS13/Shiptest/pull/1237)
[#1128: 'Pubby class remake' by spockye at commit d1bd49bba3](https://github.com/Shiptest-SS13/Shiptest/pull/1128)
[#1213: 'The Trinea' by someguyjust at commit 85a83e19bd](https://github.com/Shiptest-SS13/Shiptest/pull/1213)
[#1206: 'Rebalances Xenobio aspects' by Ketrai at commit fd227523fd](https://github.com/Shiptest-SS13/Shiptest/pull/1206)
[#132: 'Readds Explosive Decompression' by MarkSuckerberg at commit 4641e3268b](https://github.com/Shiptest-SS13/Shiptest/pull/132)
[#1236: 'Grand Prosthetics Rework' by GalacticRuler at commit 7f25b3613e](https://github.com/Shiptest-SS13/Shiptest/pull/1236)

**Issue Description**
The survivor suit lacks a hood object icon, which prevents you from adding goliath hides to it, as you need something to click on.

**Comment by redguy999** [comment]
you can still add plates to it, if you have the hood up.

**Comment by FalloutFalcon** [comment]
Fixed in #2530
