### ISSUE TITLE
Helm console does not work, NTnet relay machine gets spawned whenever the console's monitor is disconnected with a screwdriver.

### ISSUE THREAD

**Issue by horsebeater** [shiptest-ss13/Shiptest#1326]
Issue reported from  Round ID: [1001](https://shiptest.ga/stats/rounds/1001) (Shiptest)

Reporting client version: 514.1585

When using the helm console, the console showed the area around it where the overmap was supposed to be. After closing out of the console and attempting to open it again, nothing happened. I screwdrivered the console to disconnect the monitor and then screwdrivered it again to reconstruct it. This somehow spawned a NTnet quantum relay machine.
![relay](https://user-images.githubusercontent.com/99220987/178132136-5068bf7c-2f2a-47e7-8f45-da0ebe5f14d8.png)

**Comment by Zevotech** [comment]
its free materials :]
