### ISSUE TITLE
Using the ",m" key to speak Proto-Moth Pidgin causes the ",m" to still show up in your speech.

### ISSUE THREAD

**Issue by redguy999** [shiptest-ss13/Shiptest#1347]
Issue reported from  Round ID: [1014](https://shiptest.ga/stats/rounds/1014) (Shiptest)

Reporting client version: 514.1584

I've seen this in previous rounds, but it seems to be just this language.

**Comment by tiramisuapimancer** [comment]
This is most likely because of the mouse language sharing the same key

**Comment by meemofcourse** [comment]
fixed in #2414
