### ISSUE TITLE
Supply Pods Remove Pipes and Wires[BUG]

### ISSUE THREAD

**Issue by coleminerman** [shiptest-ss13/Shiptest#1355]
## Testmerges:
[#1270: 'shipowners v1' by tmtmtl30 at commit d4f1c2a4b9](https://github.com/Shiptest-SS13/Shiptest/pull/1270)
[#1299: '[TESTMERGE REQUIRED] Fix various runtimes, enables Initialize SHOULD_NOT_SLEEP' by noelle-lavenza at commit 658e8f0d18](https://github.com/Shiptest-SS13/Shiptest/pull/1299)
[#1349: '[READY][TM-REQ] Ports the CBT and TGUI refactors from /TG/' by ZephyrTFA at commit 926fff1e2d](https://github.com/Shiptest-SS13/Shiptest/pull/1349)

## Reproduction:
Launch a supply pod at a tile with pipes and wires, set in reverse mode.

**Comment by ZephyrTFA** [comment]
That's what reverse mode does, it will pull all items on the tile that aren't a turf.
