### ISSUE TITLE
[BUG] Metis spawns with untriggered object spawners

### ISSUE THREAD

**Issue by Recoherent** [shiptest-ss13/Shiptest#1370]
## Round ID:
[1025](https://shiptest.ga/stats/rounds/1025)

## Reproduction:
Load in a Metis. Five specific object spawners for certain enemies fail to trigger and instead leave a (player-visible) debug object behind.
All appear to be random threat spawners ( /obj/effect/spawner/lootdrop/randomthreat )

I'm just sort of presuming this has at least something to do with #1146 since it changed how these are intended to spawn, but apparently not correctly.

![image](https://user-images.githubusercontent.com/10237657/180493292-9a960857-be5a-4c1d-a6fe-20fdaa3d2759.png)

**Comment by triplezeta** [comment]
fixed by #1400
