### ISSUE TITLE
[BUG] Numbers in character names don't work

### ISSUE THREAD

**Issue by Sweettoothart** [shiptest-ss13/Shiptest#1386]
## Testmerges:
**[#1299: '[TESTMERGE REQUIRED] Fix various runtimes, enables Initialize SHOULD_NOT_SLEEP' by noelle-lavenza at commit d436e77b06](https://github.com/Shiptest-SS13/Shiptest/pull/1299)
[#1372: 'to chat fails silently again' by ZephyrTFA at commit 1fa3c0afe6](https://github.com/Shiptest-SS13/Shiptest/pull/1372)
[#1325: 'Init Time Reduction for Developers' by MarkSuckerberg at commit e42c879716](https://github.com/Shiptest-SS13/Shiptest/pull/1325)
[#1374: 'adjusts reaction priorities to stop bugs' by tmtmtl30 at commit 6653cf9e5d](https://github.com/Shiptest-SS13/Shiptest/pull/1374)
[#1205: 'Overmap Expansion #4' by retlaw34 at commit 063bcc07c5](https://github.com/Shiptest-SS13/Shiptest/pull/1205)
[#1213: 'The Trinea' by Sylphily at commit 837b5b2b61](https://github.com/Shiptest-SS13/Shiptest/pull/1213)
[#1313: 'Aegis class long term care vessel' by Draggeru at commit 2dfbffab2d](https://github.com/Shiptest-SS13/Shiptest/pull/1313)
[#1363: 'SRM Glaive-Class Hunter Ship' by SweetBlueSylveon at commit 98ef30d37d](https://github.com/Shiptest-SS13/Shiptest/pull/1363)**

## Reproduction: Select a character with numbers in the name. Watch with horror as the numbers vanish leaving your ipc a shell of the person they once were.

**Comment by Recoherent** [comment]
fixed by #1387 i'm silly
