### ISSUE TITLE
[BUG] Atmos pipes spawning above tiles when loaded in ruins

### ISSUE THREAD

**Issue by triplezeta** [shiptest-ss13/Shiptest#14]
## Reproduction:

Observed with the Deep storage ruin: all atmos piping spawned above the tiles rather then below. No idea what causes this.

**Comment by AsciiSquid** [comment]
Checked deepstorage.dmm, seems to be mapped using the /visible pipe variants, which override tile layering. So it's likely not a code issue at least.

**Comment by triplezeta** [comment]
what the fuck!

okay but this Does happen with other ruins, so. idk

**Comment by Cenrus** [comment]
this issue is no more (see #151)
