### ISSUE TITLE
[BUG] Having your hands full during dissection doesn't drop a paper to the floor

### ISSUE THREAD

**Issue by thgvr** [shiptest-ss13/Shiptest#1403]
## Reproduction:
Perform a research dissection with, say, hemostat and scalpel in either hand. The papers containing the points won't drop to the floor, and will instead not exist.

**Comment by Zevotech** [comment]
same goes for surveying

**Comment by MitztheKat** [comment]
can confirm the surveying paper drop issue, I guess this applies for dissection too now.

**Comment by triplezeta** [comment]
tested this on localhost, issue is occurring on latest master. Investigating further

**Comment by triplezeta** [comment]
testing on dissection, cannot reproduce this issue. I have a fix for the surveying issues that will go up momentarily
![image](https://user-images.githubusercontent.com/51932018/182041552-a9e18796-1fda-4e2e-9d98-b5c421f646e3.png)
