### ISSUE TITLE
[BUG] Gibs from butchering can fly way too far

### ISSUE THREAD

**Issue by JotSeal** [shiptest-ss13/Shiptest#1407]
## Round ID:

[1049](https://shiptest.ga/stats/rounds/1049)

## Reproduction:

- Kill a carp 
- Butcher the carp near the edge of where the water meets the beach
- Observe as the gibs fly very far away (possibly), butchering a carp in the middle of a body of water does not produce the same effect

I was told by an admin to submit a bug report and only got around to it after a bit, sorry if this is not well detailed.

**Comment by Yellow-Mushroom** [comment]
I have seen this happen a few times without water this weeks uptimes. It seems recently some gibs decide to shoot upwards of 20 tiles away

**Comment by triplezeta** [comment]
> I have seen this happen a few times without water this weeks uptimes. It seems recently some gibs decide to shoot upwards of 20 tiles away

it's definitely not a recent issue, this has happened as far back as pre-shiptest days

**Comment by Erikafox** [comment]
p sure this got fixed
