### ISSUE TITLE
[BUG] Kepori and Vox prosthetic limbs don't correctly apply on spawning in

### ISSUE THREAD

**Issue by tiramisuapimancer** [shiptest-ss13/Shiptest#1426]
## Round ID:
tested locally on latest master

## Testmerges:
tested locally on latest master

## Reproduction:
Despite showing up properly in character setup, (ish, which may be an issue with icon states)
![image](https://user-images.githubusercontent.com/32314478/182690540-dc7749e8-261d-43d0-9bbb-70d4884a366f.png)

actually spawning into the game as a Kepori or a Vox will still incorrectly give you the humanoid prosthetic limbs
![image](https://user-images.githubusercontent.com/32314478/182690488-6fd4c240-e7f1-47c3-9cdc-c44145de4989.png)

Additionally, said limbs certainly exist and function properly if manually reapplied,
![image](https://user-images.githubusercontent.com/32314478/182691236-11aa9360-5314-417c-97f7-8aacdb30ae50.png)
though for some reason, once I edited the vox's arm to be a proper vox prosthetic, their prosthetic leg updated its icon to the correct one, despite confirming that it is not actually the vox one in VV.

**Comment by drawsstuff** [comment]
I'm no coder so this flies over my head, but if you need anything sprite wise let me know.

**Comment by TallDeekus** [comment]
@drawsstuff Vox Bionicle set.


Oh wait you mean related to the issue, my bad.
