### ISSUE TITLE
Digitigrade variations only working on alt style jumpsuits

### ISSUE THREAD

**Issue by thgvr** [shiptest-ss13/Shiptest#1429]
## Round ID: [1063](https://shiptest.ga/stats/rounds/1063)
See title. Suit slot items work just fine, and the legs don't squish so I think it has to do with update overlays or something. On the bright side, this is one of the last bugs I can think of with jumpsuits.

![image](https://user-images.githubusercontent.com/81882910/182753815-749d0903-d8f4-4560-8927-b79d6a954f83.png)

**Comment by triplezeta** [comment]
wgwgwgyuhaugah

**Comment by thgvr** [comment]
I forgot this exists

Still happens, and I'm pretty sure it only happens if female masking things are applied.

**Comment by thgvr** [comment]
this is fixed since I removed female sprite masking from stuff
