### ISSUE TITLE
Railings do not refund materials on decon

### ISSUE THREAD

**Issue by Lianvee** [shiptest-ss13/Shiptest#1440]
Issue reported from Round ID: [1075](https://shiptest.ga/stats/rounds/1075) (Shiptest)

Reporting client version: 514.1584

When de-constructing metal railings, their refund of materials isn't handed out, it instead comes up with nothing.
The cost of building one is 3 iron rods which is equivalent to 1.5 sheets of iron.

**Comment by ZephyrTFA** [comment]
I consider this fine. Not sure you can justify cutting apart rods of metal and getting the rods back fresh.
Consider making a PR having it where you can weld them apart instead and get 1-2 rods back.
