### ISSUE TITLE
[BUG] solars just dont work now

### ISSUE THREAD

**Issue by triplezeta** [shiptest-ss13/Shiptest#1458]
## Round ID:

happened on localhost

## Testmerges:

N/A

## Reproduction:

build solars
![image](https://user-images.githubusercontent.com/51932018/184548873-d4a1191a-4da3-4182-a251-4c29098f96fa.png)

**Comment by triplezeta** [comment]
nvm they work
![image](https://user-images.githubusercontent.com/51932018/184548903-dbc5f5fc-2449-42c3-bce3-a4ba0bf8128c.png)

**Comment by Latentish** [comment]
A more complete version of this issue can be found in my own bug report. They in fact DO NOT work properly

**Comment by MarkSuckerberg** [comment]
~0:01 closing time, lesgoooo
