### ISSUE TITLE
[BUG] IPC organ manipulation cancels itself

### ISSUE THREAD

**Issue by Recoherent** [shiptest-ss13/Shiptest#1466]
## Round ID:
[1087](https://shiptest.ga/stats/rounds/1087)

## Testmerges:
#1205
#1317
#1438
#1375 
#1391 
#1445
#1363
#1354
#1344
#1457
#1460
#1461
#1462
#1456
#1455
#1453
#1452

## Reproduction:
Attempt prosthesis organ manipulation on an IPC chest, then try to screwdriver it open as the first step of the surgery. This cancels the surgery. Assumedly happens with other surgery options.

**Comment by Zevotech** [comment]
happens with mechanical repair as well. probably caused by #1317
