### ISSUE TITLE
[BUG] Phorids, when breathing out of anything but phorid internals tanks, act as if they are breathing an incorrect gas

### ISSUE THREAD

**Issue by Calyxman** [shiptest-ss13/Shiptest#1472]
## Testmerges:
The following pull requests are currently test merged:
[#1391: 'Aegis class long term care vessel(But again since VSCODE wanted to break.)' by Draggeru at commit 2410430d38](https://github.com/Shiptest-SS13/Shiptest/pull/1391)
[#1205: '[MDB IGNORE] [IDB IGNORE] Overmap Expansion #4' by retlaw34 at commit 072d1adbec](https://github.com/Shiptest-SS13/Shiptest/pull/1205)
[#1457: 'Interdiction' by ZephyrTFA at commit 7ad4131818](https://github.com/Shiptest-SS13/Shiptest/pull/1457)
[#1323: 'Faction Radio Channels & Department Radio Removal' by Apogee-dev at commit f247ae36a0](https://github.com/Shiptest-SS13/Shiptest/pull/1323)
[#1469: 'Hud restyle' by retlaw34 at commit 1560892855](https://github.com/Shiptest-SS13/Shiptest/pull/1469)
[#1462: 'Inteq Hound-class Corvette' by Apogee-dev at commit 6e9a017719](https://github.com/Shiptest-SS13/Shiptest/pull/1462)
[#1460: 'BYO remap' by triplezeta at commit 4ec134f229](https://github.com/Shiptest-SS13/Shiptest/pull/1460)
[#1455: 'Even more more runtime fixes' by MarkSuckerberg at commit b68159078a](https://github.com/Shiptest-SS13/Shiptest/pull/1455)
[#1453: 'Rebalances & reorganizes cargo crates' by tmtmtl30 at commit aaed278e22](https://github.com/Shiptest-SS13/Shiptest/pull/1453)
[#1456: 'Gun dealer ship changes - more ammo, inteq weaponry, artificers and corpsmen' by Calyxman at commit db24038b7f](https://github.com/Shiptest-SS13/Shiptest/pull/1456)
[#1452: 'Delta Remap' by Apogee-dev at commit 9a5f84fef5](https://github.com/Shiptest-SS13/Shiptest/pull/1452)
[#1363: 'SRM Glaive-Class Hunter Ship' by SweetBlueSylveon at commit 03881e4efb](https://github.com/Shiptest-SS13/Shiptest/pull/1363)
[#1445: 'Skipper update' by triplezeta at commit e0b0fc42da](https://github.com/Shiptest-SS13/Shiptest/pull/1445)

## Reproduction:
Be a plasmaman.
Breathe environmental plasma, plasma from a regular tank or any other source of plasma. Plasma internals tanks (the starting ones) work fine, though.
Watch as you die.

**Comment by Sylphily** [comment]
what the fuck

**Comment by Calyxman** [comment]
yea

**Comment by SomeguyManperson** [comment]
Looks like the maximum pressure for breathing is 50 kpa, which seems to apply to other lungs and other gasses (too much oxygen causes normal lungs to choke on it)
Issue here is the plasma tank starts at 101 kpa, while the belt tank starts at a survivable 17, and atmospheric plasma might end up over the safe threshold especially if it's the only thing in the air
