### ISSUE TITLE
titanium glass shuttle windows unable to be secured. 

### ISSUE THREAD

**Issue by Havaren** [shiptest-ss13/Shiptest#1499]
Issue reported from  Round ID: [1105](https://shiptest.ga/stats/rounds/1105) (Shiptest)

Reporting client version: 514.1582

titanum  glass shuttle windows cannot be secured unless built on a grill.

**Comment by triplezeta** [comment]
can you give more details on your process

**Comment by triplezeta** [comment]
![image](https://user-images.githubusercontent.com/51932018/186565737-0c16a8bd-2aaa-4acb-998f-3bfa37a72b45.png)
![image](https://user-images.githubusercontent.com/51932018/186565747-af3c348f-e78d-449e-8b14-f46e886cebe4.png)
nvm i did it
