### ISSUE TITLE
[BUG]HALLUCINATIONS DONT GO AWAY

### ISSUE THREAD

**Issue by PrefabQuasar** [shiptest-ss13/Shiptest#1500]
## Testmerges:
The following pull requests are currently test merged:
[#1391: 'Aegis class long term care vessel(But again since VSCODE wanted to break.)' by Draggeru at commit 2410430d38](https://github.com/Shiptest-SS13/Shiptest/pull/1391)
[#1205: '[MDB IGNORE] [IDB IGNORE] Overmap Expansion #4' by retlaw34 at commit 37bd38e065](https://github.com/Shiptest-SS13/Shiptest/pull/1205)
[#1457: 'Interdiction' by ZephyrTFA at commit c796ca0df3](https://github.com/Shiptest-SS13/Shiptest/pull/1457)
[#1455: 'Even more more runtime fixes' by MarkSuckerberg at commit 3785510461](https://github.com/Shiptest-SS13/Shiptest/pull/1455)
[#1453: 'Rebalances & reorganizes cargo crates' by tmtmtl30 at commit e6bd62113a](https://github.com/Shiptest-SS13/Shiptest/pull/1453)
[#1456: 'Gun dealer ship changes - more ammo, inteq weaponry, artificers and corpsmen' by Calyxman at commit db24038b7f](https://github.com/Shiptest-SS13/Shiptest/pull/1456)
[#1452: 'Delta Remap' by Apogee-dev at commit ae0fc2780b](https://github.com/Shiptest-SS13/Shiptest/pull/1452)
[#1471: 'Glasses offset for IPCs' by tiramisuapimancer at commit ed06c55040](https://github.com/Shiptest-SS13/Shiptest/pull/1471)
[#1490: 'sorts every single suit sprite into different icon files based on function' by triplezeta at commit 04be8f2833](https://github.com/Shiptest-SS13/Shiptest/pull/1490)
[#1481: 'Schmiedeberg-Class Remap' by MemedHams at commit e93eba3cea](https://github.com/Shiptest-SS13/Shiptest/pull/1481)

## Reproduction:
take the RDS quirk, any hallucinations you experience that result in percieved species changes for you or other people, like the fake polymorph hallucination, will NEVER GO AWAY UNLESS YOU RELOG, this is not good

**Comment by Yellow-Mushroom** [comment]
Is this the only thing that goes wrong that stays permanent in relation to RDS symptoms?

**Comment by PrefabQuasar** [comment]
just the transformations
