### ISSUE TITLE
[FEATURE] piratespeak in libertatia

### ISSUE THREAD

**Issue by rekuli** [shiptest-ss13/Shiptest#1523]
so you get pirate speech if you use the pirate captain headgear that you start with in the libertatia ship. not practical to sacrifice your headslot for it and i think it should be moved to a pirate jumpsuit/sailor suits. but the worst part is your crew has no way to acquire the language themselves.i tried putting on the sailor suit and the bandanas found in the locker but they didnt give me the language. a bit of a problem eh?

**Comment by Sylphily** [comment]
I believe this is just, a sideaffect of the hate, which is more or less a gag item, probably should be removed

**Comment by PiperDoots** [comment]
We are planning on removing pirate speak as a whole in the near future as part of a full language overhaul anyway, so no real need for this to be a thing.

**Comment by ZephyrTFA** [comment]
We are?

**Comment by triplezeta** [comment]
we are?

**Comment by PiperDoots** [comment]
I mean it was in the design doc tori wrote? I think?

**Comment by PiperDoots** [comment]
![image](https://user-images.githubusercontent.com/90694223/188165131-4fca87e4-8eba-4a2d-a957-c3f0c4fe9e91.png)

**Comment by triplezeta** [comment]
oh ok

**Comment by ZephyrTFA** [comment]
Oh we as in lore. I don't read up on the proposed lore changes because even if I did I would forget

**Comment by TallDeekus** [comment]
> Oh we as in lore. I don't read up on the proposed lore changes because even if I did I would forget

Should get a someone as a secretary to do that for you, joking.
