### ISSUE TITLE
[BUG] Turning on your internals while wearing a bandanna on your head causes your beard to disappear

### ISSUE THREAD

**Issue by Hibou48888** [shiptest-ss13/Shiptest#1527]
Yeah I know this sounds absurd but just bear with me

## Round ID: 
Unknown, been happening the last few weeks

## Testmerges:
N/A

## Reproduction:
Wear the red bandanna available from the loadout menu. Use it once in hand to turn it into a hat. Place it in your headwear slot. Equip an oxygen mask and some kind of O2 bottle. Turn on your internals. Turn off your internals. Voila, the bandanna tied around your head has reverted to its mask form despite still being in your head slot, and also you have no beard. 

Before toggling internals:
![notbald](https://user-images.githubusercontent.com/7544968/188278643-480e7b05-1546-422d-9b10-b421bb0c1066.png)
![notbald_equip](https://user-images.githubusercontent.com/7544968/188278648-80ff4cb5-86e3-4d1f-a082-1a0bf8b4fa55.png)

After toggling internals:
![BALD](https://user-images.githubusercontent.com/7544968/188278674-15b7138d-4e33-4962-97e3-90f6e8202802.png)
![bald_equip](https://user-images.githubusercontent.com/7544968/188278677-2e4c2e33-5ea8-486a-b16a-8dff50e0eb65.png)

**Comment by triplezeta** [comment]
I... huh???

**Comment by Hibou48888** [comment]
Yeah I don't even know. Lemme know if there's anything I can do to clear things up from my end.
