### ISSUE TITLE
Remove concentration camp/ Auschwitz references from slime rancher ruin

### ISSUE THREAD

**Issue by JukeJukestar** [shiptest-ss13/Shiptest#1547]
![image](https://user-images.githubusercontent.com/76008882/189500012-0e3c7bcc-7402-4987-9cf1-12df409479c8.png)

The slime rancher ruins' money room is very clearly a reference to nazi concentration camps. please remove this.
If it was just one of these things it could be ruled off as coincidence, but this is clearly a concious reference.
- showers
- button is called "silence button"
- gas input
- gas mask signs

Gameplay wise there is always gonna be some sort of paralel to be drawn, but this is very clearly intentionally making it look like a nazi concentration camp

**Comment by ZephyrTFA** [comment]
First of all who the fuck added this ruin

**Comment by Ms-Mee** [comment]
#44, is it not?

**Comment by Yellow-Mushroom** [comment]
To be fixed with #1549

**Comment by Erikafox** [comment]
#1552
