### ISSUE TITLE
[BUG] Glaive has planetary turfs with infinite atmos.

### ISSUE THREAD

**Issue by Erikafox** [shiptest-ss13/Shiptest#1651]
## Round ID:
[1233](https://shiptest.ga/stats/rounds/1233)

## Testmerges:
#1486 
#1550 

## Reproduction:
Spawn the Glaive (srm_glaive.dmm)
Blow a hole in it
Watch the infinite space wind from your cozy planetary turfs 

A quick glance says that it has water, grass, and dirt tiles.

https://user-images.githubusercontent.com/94164348/209579686-0d38ed32-d1e8-4a29-91f1-05037fbd5547.mp4

**Comment by Latentish** [comment]
Guess its time to SUBTYPE them
