### ISSUE TITLE
[BUG] Fax Machine GUIs are broken

### ISSUE THREAD

**Issue by meemofcourse** [shiptest-ss13/Shiptest#1658]
## Round ID:
N/A. Discovered on a local build.

## Reproduction:
Interact with a fax machine (long-range or not), cry at the blank page.
![imagen](https://user-images.githubusercontent.com/75212565/210266017-ba89cc87-6f24-462b-b847-7b4b79749e74.png)
![imagen](https://user-images.githubusercontent.com/75212565/210266022-982c7537-f954-4821-8142-5b1434dd08c8.png)

**Comment by BarteG44** [comment]
yeah it's been like that for a while now

**Comment by meemofcourse** [comment]
better submit it late than never i guess
