### ISSUE TITLE
Adds dwarves from /tg/

### ISSUE THREAD

**Issue by AverageUser67** [shiptest-ss13/Shiptest#1668]
### Related Pull Request on other codebase:

(https://github.com/tgstation/tgstation/pull/49579)

### Additional Info:

In my opinion they should spawn on asteroids or lava planets, it'd be cool to visit an asteroid and see a whole ass fortress carved into the rock.

**Comment by AverageUser67** [comment]
Note: I'm no coder, I'm just an advocate of inhabited space objects.

**Comment by Sun-Soaked** [comment]
Don't we already have a Dwarf race? 

I vividly remember nerfing it

**Comment by AverageUser67** [comment]
Yeah we do, I don't know anything about byond witchery and black magic but I imagine it'd be relatively simple to change the spawn race to our dorfs

**Comment by Erikafox** [comment]
we're not interested in more ghostroles
