### ISSUE TITLE
[BUG] First-aid kits dropped by hermits are empty

### ISSUE THREAD

**Issue by Derpguy3** [shiptest-ss13/Shiptest#1672]
Issue reported from  Round ID: [1249](https://shiptest.ga/stats/rounds/1249) (Shiptest)

Reporting client version: 514.1589

Occasionally hermits drop first-aid kits when killed, but they spawn completely empty of contents. Probably using the empty subtype of first-aid kits.

**Comment by Erikafox** [comment]
resolved by #1940
