### ISSUE TITLE
[BUG] Colonial Minutemen General Coat is missing inhand sprites

### ISSUE THREAD

**Issue by Derpguy3** [shiptest-ss13/Shiptest#1679]
Issue reported from  Round ID: [1253](https://shiptest.ga/stats/rounds/1253) (Shiptest)

Reporting client version: 514.1589

**Testmerges**
[#1659: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit 772422cd50](https://github.com/Shiptest-SS13/Shiptest/pull/1659)
[#1665: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit 2b77210159](https://github.com/Shiptest-SS13/Shiptest/pull/1665)
[#1635: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit cc04b8bd48](https://github.com/Shiptest-SS13/Shiptest/pull/1635)
[#1637: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit 41e05abe81](https://github.com/Shiptest-SS13/Shiptest/pull/1637)
[#1646: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit 97214773c6](https://github.com/Shiptest-SS13/Shiptest/pull/1646)
[#1653: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit e2472bc537](https://github.com/Shiptest-SS13/Shiptest/pull/1653)
[#1669: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit 20d1bc04f3](https://github.com/Shiptest-SS13/Shiptest/pull/1669)
[#1612: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit 3ba3803191](https://github.com/Shiptest-SS13/Shiptest/pull/1612)
[#1536: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit f0d28e7e4a](https://github.com/Shiptest-SS13/Shiptest/pull/1536)
[#1664: 'GITHUB API ERROR: RATE LIMITED' by GITHUB API ERROR: RATE LIMITED at commit 10f39416e6](https://github.com/Shiptest-SS13/Shiptest/pull/1664)
(The names of the TMs got bugged somehow but the links still work)
**Description**
The General's coat has its on-mob sprite, but its missing the inhand sprites.

**Comment by spockye** [comment]
![image](https://user-images.githubusercontent.com/79304582/212024335-33ac089c-0309-4e62-9c89-5d032adc0552.png)

it currently doesn't have a item_sprite, same with the syndicate captain Vest.
