### ISSUE TITLE
[BUG] /floor/plating/beach/sand doesn't render properly most of the time.

### ISSUE THREAD

**Issue by Latentish** [shiptest-ss13/Shiptest#1691]
## Reproduction:
![image](https://user-images.githubusercontent.com/55075747/212447943-ce8bbe81-74c6-4a2b-8b2d-096ba2a0d584.png)
Spawn one of the beach planet ruins. Most of the beach tiles used are /turf/open/floor/plating/beach/sand which is from the beach biodome ruin for lavaland. They need to have either /turf/open/floor/plating/asteroid/sand/dense/lit or /turf/open/floor/plating/asteroid/sand/lit. The beach biodome tile does not render properly most of the time as seen in the above screenshot.

**Comment by Latentish** [comment]
The solution is to replace those sand tiles in all 4 beach ruins and maybe find out why the biodome one doesn't work right.

**Comment by Erikafox** [comment]
reopen if we didn't fix this but I'm pretty sure we did
