### ISSUE TITLE
[BUG] Floor lights are invisible when unpowered or disabled

### ISSUE THREAD

**Issue by goober3** [shiptest-ss13/Shiptest#1694]
## Reproduction:

1. Spawn a floor light in an unpowered area. 
2. Weep

![floorlight](https://user-images.githubusercontent.com/118859017/212493593-fa90d291-6ff9-4725-9c23-0905d906a792.gif)

**Comment by GenericDM** [comment]
Fixed in #2424 I think? Regardless, not a problem anymore.
