### ISSUE TITLE
[BUG] Sawn-off polymer survival rifle has no sprite 

### ISSUE THREAD

**Issue by Calyxman** [shiptest-ss13/Shiptest#1697]
## Round ID:

Report from Sector Echo 13. AFAIK, they haven't done anything that could cause this.
SE13 Round ID was 529.

## Testmerges:

N/A. 

## Reproduction:

Step 1. Get saw/knife/whatever, but I used a hatchet
Step 2. Open bolt of rifle
Step 3. Cut off barrel
Step 4. Notice lack of sprite
![image](https://user-images.githubusercontent.com/81567866/212607453-8c09f84d-c573-4829-a1b3-74fdcebaebc7.png)
It has a small icon sprite in the right-click menu but no sprite on the floor or in-hand.
On further investigation, the sprite was finicky and didn't show for a bit, but it used the Illestren sprite. 
It also used the Illestren description.

**Comment by Calyxman** [comment]
I got permission from the Sector Echo admins to take the image in-round and post it here

**Comment by Zevotech** [comment]
this is kind of a part of a bigger problem where a LOT of sprites are randomly missing. Dragonslayers spear, plate armor and reactive armor also are fucked up and lack sprites.

**Comment by SomeguyManperson** [comment]
Seems to have been fixed
