### ISSUE TITLE
Non-diagonal-smoothing titanium walls cannot be constructed

### ISSUE THREAD

**Issue by Pontenerd** [shiptest-ss13/Shiptest#173]
Issue reported from  Round ID: [127](https://scrubby.melonmesa.com/round/127) (Shiptest)

Reporting client version: 514.1557

![image](https://user-images.githubusercontent.com/68692362/130131154-fac58d35-8ec8-463c-89c7-b9e99c825b71.png)

**Comment by HighPrincessErinys** [comment]
1. Actual ship class is the Carina.
2. This is probably because of the fucking atrocious cargo pod explosions because I recall that these were fine earlier.

**Comment by MarkSuckerberg** [comment]
This is a general problem with diagonal walls in general, especially shuttle/titanium walls as there are both non-diagonal-smoothing and diagonal-smoothing types, but only the diagonal-smoothing types are constructable.

**Comment by ZephyrTFA** [comment]
Best I can do for you is making it possible to make walls not smooth at all. But this will be even worse so just going to go ahead and close this.
If you want those doors to smooth with the wall add them to the smoothing group via a map override
