### ISSUE TITLE
[BUG] Warden vests have no sprites

### ISSUE THREAD

**Issue by Latentish** [shiptest-ss13/Shiptest#1734]
## Reproduction:
Try to use the warden vests that aren't the /nt version.
The following armor vests do not have sprites:
/obj/item/clothing/suit/armor/vest/security/warden
/obj/item/clothing/suit/armor/vest/security/warden/alt

![image](https://user-images.githubusercontent.com/55075747/214487236-032bd88b-3c30-41a2-a355-4c8b2597b1d9.png)
![image](https://user-images.githubusercontent.com/55075747/214487272-7ae01792-276c-462b-aa03-ae20f8a7218d.png)

**Comment by Hibou48888** [comment]
Took a look at this and it looks like it's fixed? No idea when or what PR fixed it, but these vests have sprites in the current code. Here's a screenshot from a local instance: 
![image](https://user-images.githubusercontent.com/7544968/235824494-73083532-5b7d-45a8-ad26-0f493955bc93.png)

**Comment by meemofcourse** [comment]
fixed in #1747 I Think.
