### ISSUE TITLE
Maid box from loadout spawns inside loadout box

### ISSUE THREAD

**Issue by ArdentSpark** [shiptest-ss13/Shiptest#1743]
Issue reported from  Round ID: [1289](https://shiptest.ga/stats/rounds/1289) (Shiptest)

Reporting client version: 514.1585

Maid box spawns inside the loadout box, creating a nested box which is impossible to achieve in game. We don't have code that disables accessing nested boxes so this makes the maid box a wierdly powerful loadout item for inventory stacking

I know people here dislike that, so I'm reporting this because I want my maid outfit without it being removed because of gaming!

**Comment by Bokkiewokkie** [comment]
One evil solution is making it impossible to put anything back in that box (forcing you to fold it into a regular box to use it and thus taking it out of the bag)

**Comment by Orchidthederg** [comment]
Sorry to necropost (i plan on making a fix), but I think it might be best to see about making the loadout option just put the maid box contents directly into the loadout box, since a box you can't put anything into sounds... Potentially rather abuseable, looking forward.

**Comment by meemofcourse** [comment]
murdered in #2732
