### ISSUE TITLE
[BUG] Skipper-class distro leaks

### ISSUE THREAD

**Issue by CliffracerX** [shiptest-ss13/Shiptest#1757]
## Reproduction:
Spawn in a new Skipper-Class Heavy Cruiser from the Purchase Ship menu.  Plasma enters the O2->airmix line through the 3-way manifold's corner pipe that connects it to O2->burnmix line.  Similarly, the N2->airmix line gets contaminated by the N2->burmix manifold.  Removing the corner pipes or replacing the manifolds with straight vertical pipes, waiting for residual gasses to clear, and performing a Fix Air shows that the issue is resolved; no additional plasma enters O2->Distro, nor O2 into the N2->Distro line.  Not clear to me if this is a mapping bug, or some haunted activities in the pipenet connection code.

Screenshot highlighting the problem pipes & plasma'd distro chamber.
![image](https://user-images.githubusercontent.com/2958111/218019716-fe0d4cdc-9a48-4564-9f55-e2fdd859b393.png)

**Comment by CliffracerX** [comment]
Update: this does _not_ appear to be present on live as of the latest test, which suggests it might be fixed by something currently being testmerged _or_ that it's a bug unique to local servers in some form.

**Comment by Erikafox** [comment]
This is probably window spawners being cursed, let me check to confirm.

**Comment by Erikafox** [comment]
![StrongDMM_iFYdsbmK3u](https://user-images.githubusercontent.com/94164348/218241776-aac6febd-7053-4521-9923-7931914716b8.png)
yea
