### ISSUE TITLE
[BUG] Mining sand on beach worlds makes it darker

### ISSUE THREAD

**Issue by nightmarish-warlord** [shiptest-ss13/Shiptest#1765]
## Reproduction:

![image](https://user-images.githubusercontent.com/80289853/218299397-6c1e6b21-11bc-43b9-90d5-fd64b82f9fe3.png)

go to beach planet, dig holes, area dug has no natural lighting

**Comment by Erikafox** [comment]
also happens with sandworld sand. 
Looks like what's happening is the light_range is getting set to 0 after the tiles are mined.

**Comment by Sun-Soaked** [comment]
fixed in overmap 4.2
