### ISSUE TITLE
[BUG] White sand piles are missing sprites

### ISSUE THREAD

**Issue by Derpguy3** [shiptest-ss13/Shiptest#1786]
Issue reported from  Round ID: [1347](https://shiptest.ga/stats/rounds/1347) (Shiptest)

Reporting client version: 514.1589

**Test Merges**
[#1770: 'Li-tieg touchup' by BarteG44 at commit 839a33fce1](https://github.com/Shiptest-SS13/Shiptest/pull/1770)
[#1764: 'SEV Lugol-class GEC Engineering Project' by goober3 at commit 63611c632f](https://github.com/Shiptest-SS13/Shiptest/pull/1764)
[#1758: 'potentially fixes incorrect ruin turf icon_states' by tmtmtl30 at commit 0ec820ddf1](https://github.com/Shiptest-SS13/Shiptest/pull/1758)
[#1735: 'New Beach Ruin: Pirate Village' by goober3 at commit 080eb5c32b](https://github.com/Shiptest-SS13/Shiptest/pull/1735)
[#1724: 'Nanotrasen Mimir-Class Rehabilitation (Prison) Vessel' by Latentish at commit 894cc96ddf](https://github.com/Shiptest-SS13/Shiptest/pull/1724)
[#1637: 'Mapgen fixes and speedups (ignore the branch name. I'm dumb)' by tmtmtl30 at commit 41e05abe81](https://github.com/Shiptest-SS13/Shiptest/pull/1637)
[#1773: 'Removes Skeleton Spawners from jungle_demon' by Bjarl at commit adb58ada37](https://github.com/Shiptest-SS13/Shiptest/pull/1773)
[#1711: 'Holographic signs and barriers have a limited lifespan' by Apogee-dev at commit 79f8f4440e](https://github.com/Shiptest-SS13/Shiptest/pull/1711)
[#1716: 'Add the angle grinder, a tool to deconstruct structures quickly' by ritorizo at commit 7639b57aec](https://github.com/Shiptest-SS13/Shiptest/pull/1716)

**Description**
The white sand piles from sand planets are missing sprites. Uncertain if this is caused from a test merge or not.

![Screenshot 2023-02-22 173920](https://user-images.githubusercontent.com/85206687/220796451-cb38a58c-20ad-45a2-9ee2-e12a152b922d.png)
![Screenshot 2023-02-22 173934](https://user-images.githubusercontent.com/85206687/220796456-c1e6521f-228f-49a6-8dd1-6d861809a7c7.png)

**Comment by Sun-Soaked** [comment]
the sprite is missing from the file in question, lemme look for it

**Comment by Sun-Soaked** [comment]
![image](https://user-images.githubusercontent.com/45698967/220826207-47ea6b08-4cc4-44c1-b99f-85ae91467a13.png)
Fixed. PR'ing it to Overmap 4.2
