### ISSUE TITLE
[BUG] Corvus-class has disabled functional external turrets

### ISSUE THREAD

**Issue by Derpguy3** [shiptest-ss13/Shiptest#1790]
Issue reported from  Round ID: [1352](https://shiptest.ga/stats/rounds/1352) (Shiptest)

Reporting client version: 514.1589

**Description**
The Corvus-class vessel has a number of external ballistic turrets which would normally assist somewhat in shooting fauna and the likes. However, they do not actually function as intended, and simply sit there. (They're probably turned off.) They're definitely supposed to be functional, as the fauna like to break them, but there are no controls for the turrets in the ship to actually enable them.

**Comment by Derpguy3** [comment]
I played around with the Corvus-class last test and I was able to figure out the deal with the turrets

- All turrets are functional, but are off by default and need to be turned on manually before they shoot anything.
- The ship lacks a turret control panel to control all of the turrets at once.

**Comment by Erikafox** [comment]
@spockye fix please
