### ISSUE TITLE
[BUG] Having lava in your view results in FPS drops

### ISSUE THREAD

**Issue by Hardly3D** [shiptest-ss13/Shiptest#1793]
## Reproduction:
On my fairly weak machine, I've noticed that going next to a lake of lava in places such as the lava planet will result in a major FPS drop, which I feel like https://github.com/shiptest-ss13/Shiptest/pull/1569 may have something to do with this?
Might be hard to reproduce since this will likely depend on how good your computer is.

**Comment by rye-rice** [comment]
Yeah I was worried about this when I made that, performance on weaker computers, but it seemed like everyone i talked to didn't have a problem with it.

**Comment by rye-rice** [comment]
I know bay has some sort of particle pref, maybe that could help with low performance pcs while keeping the effect for high performance pcs?

**Comment by Ashturian** [comment]
I can also vouch for getting some hefty loss of FPS around lava. Not playing on the greatest rig but handles everywhere else in Shiptest just fine

**Comment by Ashturian** [comment]
Some further testing on my machine, I tried tweaking just about every var for the particles individually (max count, spawn rate, lifespan, fade, friction, gradient, colour change), and using different generators for the randomness. Nothing seemed to have an impact on the performance drain on my machine other than just disabling them completely.
