### ISSUE TITLE
Directional Lighting Sets Off Landmines

### ISSUE THREAD

**Issue by Erikafox** [shiptest-ss13/Shiptest#1861]
Issue reported from  Round ID: 1468 (Shiptest)
![image](https://user-images.githubusercontent.com/94164348/229299271-0540f48a-145c-42e3-b4cf-525f34259ff7.png)

Reporting client version: 514.1589

**Comment by thgvr** [comment]
what the hell

**Comment by Addust** [comment]
it's an integrated mine disarmament module

**Comment by SomeguyManperson** [comment]
Effects and projectiles can trigger mines
