### ISSUE TITLE
[BUG] cant see join ship menu when hosting

### ISSUE THREAD

**Issue by ballkicker1** [shiptest-ss13/Shiptest#1869]
Round id: NULL
sorry, its my first time hosting and i maybe made a stupid mistake.
i was hosting the shiptest on my computer, however, everytime i click "join game!" i get a white screen. Nothing happens and i cant even move/close the white square.
please tell me what did i do wrong and how can i fix it.

**Comment by Erikafox** [comment]
Did you run build.bat

**Comment by ballkicker1** [comment]
> Did you run build.bat

no

**Comment by MarkSuckerberg** [comment]
run that and it'll work
