### ISSUE TITLE
[BUG] The E-SG 255 Ultimate on the Jupiter class functions as a tablet if you use it inhand

### ISSUE THREAD

**Issue by BogCreature** [shiptest-ss13/Shiptest#1879]
## Round ID:
1487

## Testmerges:
[#1781: '[Needs TM] The Accelerataning' by MarkSuckerberg at commit 207243cf13](https://github.com/Shiptest-SS13/Shiptest/pull/1781)
[#1834: 'Changes the airlock sounds' by retlaw34 at commit a046829f5c](https://github.com/Shiptest-SS13/Shiptest/pull/1834)
[#1836: 'Ports some skyrat cooking equipment' by MrSamu99 at commit e419941c66](https://github.com/Shiptest-SS13/Shiptest/pull/1836)
[#1843: 'Ports mothroaches + Moth emotes' by meemofcourse at commit febdc835a8](https://github.com/Shiptest-SS13/Shiptest/pull/1843)
[#1852: 'Disks now fit in folders' by Bjarl at commit 252a6000e9](https://github.com/Shiptest-SS13/Shiptest/pull/1852)
[#1853: 'Enables Kansatsu + Minor Changes' by Bjarl at commit bce79c32ea](https://github.com/Shiptest-SS13/Shiptest/pull/1853)
[#1856: 'IPC wings' by SapphicOverload at commit 1a5cf29bfa](https://github.com/Shiptest-SS13/Shiptest/pull/1856)
[#1864: 'Tones down giant spiders' by thgvr at commit 2098414f59](https://github.com/Shiptest-SS13/Shiptest/pull/1864)
[#1666: '[DNM] Columba-class Mining Carrier' by goober3 at commit c3e6f9f3e8](https://github.com/Shiptest-SS13/Shiptest/pull/1666)
[#1871: 'General fauna sprite update' by thgvr at commit 62ccf4909c](https://github.com/Shiptest-SS13/Shiptest/pull/1871)
[#1866: 'Adds the Ancon-Class' by meemofcourse at commit eb52d990db](https://github.com/Shiptest-SS13/Shiptest/pull/1866)
[#1820: 'ports the exosuit pka from tgstation' by Bjarl at commit 7d8b06c1c7](https://github.com/Shiptest-SS13/Shiptest/pull/1820)
[#1724: 'Nanotrasen Mimir-Class Rehabilitation (Prison) Vessel' by Latentish at commit 471967dfbc](https://github.com/Shiptest-SS13/Shiptest/pull/1724)
[#1788: 'Jupiter-Class Stormrider' by Bjarl at commit 30d033437c](https://github.com/Shiptest-SS13/Shiptest/pull/1788)

## Description
I've got no idea the fucking gun has a computer the NT OS menu on it when you use it inhand

## Reproduction:
Use the E-SG 255 Ultimate on the Jupiter inhand
[Optional] Download angry birds on your gun

**Comment by BogCreature** [comment]
Okay, in looking into it further, this is the case for all E-SG 255 Ultimates, and to make matters even more confusing this is intended(???) but also it makes switching the firing modes harder for reasons I still can't divine

**Comment by TheNeoGamer42** [comment]
yeah this thing was made way back during whitesands, it uh, it's based off some weird... I think russian smart shotgun or some shit? apparently could record videos, it was weird and this gun is weird but this is am Intentional feature, though it does predate the guncode
