### ISSUE TITLE
[BUG] Prosthetic Legs do NOT get spawned by the preferences copy_to proc.

### ISSUE THREAD

**Issue by Ms-Mee** [shiptest-ss13/Shiptest#1956]
## Round ID: 
None, wasn't live on the server, just a personal investigation on local though just looking at the code I already knew what was going to be the issue.

## Reproduction:
Add prosthetic legs to character, notice distinct lack of prosthetic legs on character, spawn in, no prosthetics??

## Cause:
PR #1819, which changes the leg bodypart paths, making them no longer match the BODY_ZONE_L_LEG and BODY_ZONE_R_LEG macros. Alongside many other uses, those macros are used to define the limbs in the preferences prosthetic limbs list, and since the copy_to proc uses uses text2path to get the limb paths, using the prosthetic limbs list, when one tries to get bodypart/l_leg/robot/surplus there won't be any matching path, since the new path is bodypart/leg/left/robot/surplus.

**Comment by Ms-Mee** [comment]
Also the warning about a path for the limb not being found doesn't seem to get displayed.

**Comment by MarkSuckerberg** [comment]
bet this is fixed by #1931

**Comment by Ms-Mee** [comment]
It is, at it's current state
