### ISSUE TITLE
Ships can occasionally spawn on top of eachother

### ISSUE THREAD

**Issue by Addust** [shiptest-ss13/Shiptest#1977]
Issue reported from  Round ID: 1601 (Shiptest)

Reporting client version: 514.1589

i was playing with a BYO-class and SUDDENLY

_Mining Shuttle slams into Addust Johnson._
DEAD ON THE SPOT
NOTHING LEFT BEHIND

**Comment by Erikafox** [comment]
This sounds like a subshuttle funny. please provide a screenshot

**Comment by Addust** [comment]
it was a kilo-class ramming a BYO-class, no screenshots
