### ISSUE TITLE
[BUG] IPCs can be extracted from in lipid extractors

### ISSUE THREAD

**Issue by MitztheKat** [shiptest-ss13/Shiptest#2076]
## Reproduction:

insert (overcharged?) ipc into lipid extractor
get this 
![image](https://github.com/shiptest-ss13/Shiptest/assets/29964282/b70a14ec-677c-4c60-9561-6b9d102d141e)

**Comment by Zevotech** [comment]
https://www.youtube.com/watch?v=lL6C3AQ9Fc4

**Comment by thgvr** [comment]
HORRORS BEYOND REALITY

**Comment by tmtmtl30** [comment]
drawing blood from a stone

**Comment by Sun-Soaked** [comment]
the flesh the flesh the flesh the flesh thw

**Comment by tiramisuapimancer** [comment]
dont patch this

**Comment by meemofcourse** [comment]
one big human heart, gently beeping

**Comment by GenericDM** [comment]
No longer an issue with the removal of lipid extractors #2516
