### ISSUE TITLE
[BUG] Clicking on a ship's Join/Apply adds another Job Select tab to the Ship Selection screen

### ISSUE THREAD

**Issue by Derpguy3** [shiptest-ss13/Shiptest#2109]
Issue reported from  Round ID: 1712 (Shiptest)

Reporting client version: 514.1589

![Screenshot 2023-06-30 160429](https://github.com/shiptest-ss13/Shiptest/assets/85206687/6d22874c-fdc5-495d-9106-7341b6807071)

When you are in the ship selection screen, and you go to apply/join a ship, but go back to the ship select tab and click on another ship, another "Job Select" tab appears.

Notes
- The extra job selects functional, in the sense that having the extra tabs doesn't break anything. It just gets rather long.
- Closing the Ship Selection menu resets it back to normal upon re-opening it.

**Comment by Arturlang** [comment]
I'm handling this, 100% my fault
