### ISSUE TITLE
[BUG] Wiki verb does not work properly

### ISSUE THREAD

**Issue by meemofcourse** [shiptest-ss13/Shiptest#2148]
## Testmerges:

[#2080: 'Organizes lists in surgery files, nerfs ghetto surgery a bit' by thgvr at commit 7c182a04ff](https://github.com/Shiptest-SS13/Shiptest/pull/2080)
[#1880: 'NTSV Tegus-class Logistics Freighter' by goober3 at commit 3fd3727250](https://github.com/Shiptest-SS13/Shiptest/pull/1880)
[#1931: 'Secondary Mutcolours, Synthetics, and Lizard Prosthetics (Yes, they're synths.) (Sprites by Thgvr!)' by MarkSuckerberg at commit 19914a7358](https://github.com/Shiptest-SS13/Shiptest/pull/1931)
[#2034: 'Total Remap of the Ranger' by Latentish at commit a7a7a7a5e4](https://github.com/Shiptest-SS13/Shiptest/pull/2034)
[#2074: 'The Most Serene Solar Confederation's Most Serene Solar Starship, The Chronicle' by Bjarl at commit fb23485880](https://github.com/Shiptest-SS13/Shiptest/pull/2074)
[#2131: 'Adds sanitization redundancy for 3-hex colours' by MarkSuckerberg at commit 8009be5020](https://github.com/Shiptest-SS13/Shiptest/pull/2131)
[#1997: 'Overmap 4.7: Gas Giants, More Storms, 8 hours of work' by Bjarl at commit 4cf8087cf8](https://github.com/Shiptest-SS13/Shiptest/pull/1997)
[#2130: 'Ahelp claiming system' by MarkSuckerberg at commit a448488b90](https://github.com/Shiptest-SS13/Shiptest/pull/2130)
[#2133: 'SSlag_switch from /tg/' by MarkSuckerberg at commit dae0ec3014](https://github.com/Shiptest-SS13/Shiptest/pull/2133)
[#2137: 'Fixes improper outfit declarations' by Latentish at commit a2c345c2c6](https://github.com/Shiptest-SS13/Shiptest/pull/2137)
[#2047: 'New Lavaland Ruin: The Nanotrasen Genetics Research Facility' by Zevotech at commit c1ab67c6e8](https://github.com/Shiptest-SS13/Shiptest/pull/2047)
[#2026: 'Tiny Anywalls Fixes' by Bjarl at commit 28c837e9ec](https://github.com/Shiptest-SS13/Shiptest/pull/2026)

## Reproduction:

Using the wiki verb (and by extension the wiki button uptop) with anything beyond the main page does not properly open the wiki page in the browser, and instead lands you in an Index.php page.
![imagen](https://github.com/shiptest-ss13/Shiptest/assets/75212565/89ad2be2-0601-41f1-bd2f-0b43b9615e3d)
![imagen](https://github.com/shiptest-ss13/Shiptest/assets/75212565/ebf1ac0f-2c17-48f9-9817-eeb6573020f5)

**Comment by MarkSuckerberg** [comment]
fucg,

config issue though I think

**Comment by MarkSuckerberg** [comment]
oh wait no it's in code
https://github.com/shiptest-ss13/Shiptest/blob/03ecd6469aef639e9ee0f7eeb370b42833f0eba6/interface/interface.dm#L9
