### ISSUE TITLE
Nigiri Sushi Missing Sprite

### ISSUE THREAD

**Issue by TheIssueFairy** [shiptest-ss13/Shiptest#2162]
Issue reported from  Round ID: 1744 (Shiptest)

Reporting client version: 514.1589

Nigiri sushi doesn't have a sprite, and is invisible.

Steps to replicate:

1. Acquire ingredients
2. Use crafting menu to make nigiri sushi
3. Discover that you are holding invisible sushi.

**Comment by TheIssueFairy** [comment]
Oh, also making it consumes the bowl part of the boiled rice. I'm not sure if that's intended or not.

**Comment by meemofcourse** [comment]
do you eat your rice with or without the bowl
