### ISSUE TITLE
[BUG] you cannot hear instruments unless you are on their tile

### ISSUE THREAD

**Issue by tiramisuapimancer** [shiptest-ss13/Shiptest#222]
## Testmerges:
doesnt matter this happened before any of them

## Reproduction:
Play an instrument, realize nobody can hear you unless they are on your tile, crawl under people in order to spread tunes

**Comment by PrefabQuasar** [comment]
i didnt realize people would be able to hear if i crawled beneath them, time to do this at all times

**Comment by MarkSuckerberg** [comment]
Fixed in #225
