### ISSUE TITLE
[BUG] #2121 made the khaki and tan pants look completely the same

### ISSUE THREAD

**Issue by BarteG44** [shiptest-ss13/Shiptest#2232]
#2121  made the khaki and tan pants look completely the same

## Reproduction:
 

https://github.com/shiptest-ss13/Shiptest/assets/105491762/84ee35b1-a63e-42e0-ab84-48d93f11e1e0

(i am switching between the two with V)

**Comment by thgvr** [comment]
fun fact: the old sprite was exactly the same except for one or two pixels, not a bug

**Comment by BarteG44** [comment]
I remember the tan pants being distinctively darker. Even so it was an issue that could have been solved with the respite

**Comment by thgvr** [comment]
![image](https://github.com/shiptest-ss13/Shiptest/assets/81882910/d1e7274b-50a5-4d1e-a54d-48b4a2f58cb1)
Above is tan bottom is khaki
What would you say the difference between Tan and Khaki is anyways, in reality I forgot to delete the tan pants

**Comment by BarteG44** [comment]
Very well, maybe i was misremembering from beestation. Still i find it funny how your first solution is to remove rather than to fix

**Comment by thgvr** [comment]
I'm not sure how you'd even differentiate tan versus khaki. khaki is tan
