### ISSUE TITLE
SolGov surgery cap turns invisible upon touch.

### ISSUE THREAD

**Issue by GenericDM** [shiptest-ss13/Shiptest#2269]
Issue reported from  Round ID: 1819 (Shiptest)

Reporting client version: 514.1589

When picked up in hand, flipped around, or generally poked and prodded, the surgical cap will irreversibly turn invisible.

**Comment by Erikafox** [comment]
the cap is doing
/obj/item/clothing/head/soft/dropped()
	icon_state = "[soft_type]soft"
	flipped=0
	..()

which sets its icon state to solgov_surgerysoft

which does not exist.

**Comment by Imaginos16** [comment]
I love when I shitcode things
