### ISSUE TITLE
[BUG] docking issues

### ISSUE THREAD

**Issue by Pontenerd** [shiptest-ss13/Shiptest#229]
## Testmerges:

The following pull requests are currently test merged:
#108: '[MDB IGNORE] Baytiles/the great ship prettyfication' by retlaw34 at commit abd9fd0b09
#218: '[DNM] Swifter's Ship Emporium!' by swifterjack at commit 3d1186454b
#130: 'bay clicky noises' by retlaw34 at commit 281b0945b6
#154: 'Disable Events' by ZephyrTFA at commit f821d7d77e
#179: 'Update Define Spacing' by ZephyrTFA at commit 289cc24feb

## Reproduction:

I tried to dock at a planet with another ship, we both docked but could not find eachother, i undocked and the planet was gone

**Comment by MarkSuckerberg** [comment]
?

**Comment by Pontenerd** [comment]
The formatting is fucked up on this, I'll try fix it

**Comment by MarkSuckerberg** [comment]
I think this bug was fixed in some PR, I haven't seen it happen since around the time this issue was made. Re-open or comment if someone else sees it happen
