### ISSUE TITLE
Some Machinery is Invisible.

### ISSUE THREAD

**Issue by GenericDM** [shiptest-ss13/Shiptest#2291]
Issue reported from  Round ID: 1836 (Shiptest)

Reporting client version: 514.1589

![image](https://github.com/shiptest-ss13/Shiptest/assets/34109002/34c8669a-4118-470c-8e29-f3e9748b0107)
![image](https://github.com/shiptest-ss13/Shiptest/assets/34109002/5fda0731-91b1-4a4e-9c8c-d035774f767b)
However, inserting a blood bag does properly add the overlay.
![image](https://github.com/shiptest-ss13/Shiptest/assets/34109002/02c828a6-1427-471b-aec8-e8c3dad8f0da)

**Comment by Erikafox** [comment]
believe this is an update_appearance port issue. same happens for some previously working ammo magazines (12g drum)

**Comment by Sun-Soaked** [comment]
fixed in #2299

**Comment by GenericDM** [comment]
> fixed in #2299
