### ISSUE TITLE
[BUG] Weird asteroid darkness persisting in space dynamic encounters

### ISSUE THREAD

**Issue by triplezeta** [shiptest-ss13/Shiptest#23]
## Reproduction:

step 1: go to asteroid

step 2: undock then go to a space dynamic encounter

step 3: ???????????
![image](https://user-images.githubusercontent.com/51932018/120081246-f17cdd00-c079-11eb-97f8-21a739bd1a2e.png)

**Comment by MarkSuckerberg** [comment]
Seems resolved on round 15
