### ISSUE TITLE
[BUG] Buy a cricket, get a raven

### ISSUE THREAD

**Issue by AsciiSquid** [shiptest-ss13/Shiptest#232]
## Round ID:[165](https://shiptest.ga/stats/rounds/165)
Bought a cricket-class, got a raven-class with missing tiles in the main room, get Neo to force-load a new ship
Nobody joins my ship, I'm blaming this bug instead of anything reasonable.

## Testmerges:
#108: '[MDB IGNORE] Baytiles/the great ship prettyfication' by retlaw34 at commit abd9fd0b09
#218: '[DNM] Swifter's Ship Emporium!' by swifterjack at commit 3d1186454b
#130: 'bay clicky noises' by retlaw34 at commit 281b0945b6
#154: 'Disable Events' by ZephyrTFA at commit f821d7d77e
#179: 'Update Define Spacing' by ZephyrTFA at commit 289cc24feb

## Reproduction:
Buy a cricket, suffer.

**Comment by untrius** [comment]
I've bought several cricket-class ships on my test server with no issue, and was able to buy one on live yesterday.

**Comment by fighterslam** [comment]
Is this still an issue?
