### ISSUE TITLE
 Bees can open Apiary Doors in the Shepherd Class

### ISSUE THREAD

**Issue by PigeonLord** [shiptest-ss13/Shiptest#2320]
## Reproduction:

>make bees spawn in Sheperd Aviary
>Bees open the Apiary doors and sting you dead
>cri

**Comment by MarkSuckerberg** [comment]
containment beereach

**Comment by PigeonLord** [comment]
Closing this as https://github.com/shiptest-ss13/Shiptest/pull/2319#issue-1874568932 now addresses it
