### ISSUE TITLE
[BUG] Tactical Turtleneck breaks when worn casually.

### ISSUE THREAD

**Issue by GenericDM** [shiptest-ss13/Shiptest#2325]
Tactical Turtleneck has the option available to wear casually, but the on-mob sprites for it disappear entirely when worn as such.
![turtleneck](https://github.com/shiptest-ss13/Shiptest/assets/34109002/9bc14c05-6b52-4484-929e-12f55ea4c1c0)

**Comment by BarteG44** [comment]
Tactical stripdown
