### ISSUE TITLE
[BUG] Kepori Post Pounce Movement Slow

### ISSUE THREAD

**Issue by Slim-Pickems** [shiptest-ss13/Shiptest#2340]
## Testmerges:

 Local commit: 62a1b3ecbb81e85cddba26f36f27928545a4a715
TGS version: 5.13.7
DMAPI version: 5.6.1

## Reproduction:
As a Kepori, pounce on someone. It may cause the character to become permanently slow despite being fully healthy. First experienced as FBP. Aheal may or may not fix.

STEPS
1: As Kepori, prepare a pounce. Nothing in hand, at run speed.
2: Pounce a player.
3: Observe speed loss.

This so far has only been noted in one round, but I will be attempting to recreate this bug every round I can.
I did note a drop in mood rapidly, but it may be unrelated.

Attached his med scanner results.

This is my first report, so any tips on future reports would be greatly appreciated.

![123](https://github.com/shiptest-ss13/Shiptest/assets/144301516/8112569d-0d36-473f-85f2-665ba22dddde)

**Comment by ArdentSpark** [comment]
As a contribution to this issue, I've experienced it in the past. User's can fix it if I recall, by aggressive grabbing someone, and letting go. Which leads me to think it's a bug related to the aggressive grab part of the pounce
