### ISSUE TITLE
[BUG] The Entirety of the Komodo's Bar

### ISSUE THREAD

**Issue by Geoengi** [shiptest-ss13/Shiptest#2348]
## Testmerges:
[#2213: '(Re) Adds meteor shields' by Bjarl at commit 951e17bb35](https://github.com/Shiptest-SS13/Shiptest/pull/2213)
[#2256: 'Revamps wasteplanet_unhonorable' by Dethstorm at commit cfe47f7351](https://github.com/Shiptest-SS13/Shiptest/pull/2256)
[#2262: 'Cepheus nerfs' by Bjarl at commit 75a4f97d5a](https://github.com/Shiptest-SS13/Shiptest/pull/2262)
[#2272: 'Buildmode & Supply Pod Ports' by thgvr at commit 419326ca61](https://github.com/Shiptest-SS13/Shiptest/pull/2272)
[#2274: 'Anti-Radiation Foam' by Bjarl at commit cdd4dbf553](https://github.com/Shiptest-SS13/Shiptest/pull/2274)
[#2307: 'Adds a voice log to the wideband' by BarteG44 at commit 780707694c](https://github.com/Shiptest-SS13/Shiptest/pull/2307)
[#2316: 'Better metal rod throwing feedback' by retlaw34 at commit c0b1db6bd3](https://github.com/Shiptest-SS13/Shiptest/pull/2316)
[#2321: 'The CentCom-ening: Shiptest Edition' by meemofcourse at commit 33f3edd3be](https://github.com/Shiptest-SS13/Shiptest/pull/2321)
[#1670: 'Heron- Class!' by spockye at commit 37fa1db956](https://github.com/Shiptest-SS13/Shiptest/pull/1670)
[#2250: 'outpost tweaks & fixes: Vengeance ' by goober3 at commit e12ad21ff4](https://github.com/Shiptest-SS13/Shiptest/pull/2250)
[#2345: 'disable ion storms' by thgvr at commit 80534058a8](https://github.com/Shiptest-SS13/Shiptest/pull/2345)

## Reproduction:

When moving the Booze-O-Mat, the impassible hitbox places itself above the actual sprite, while the sprite itself preserves the ability to be interacted with a tile below it. 
![Vendor](https://github.com/shiptest-ss13/Shiptest/assets/139566513/11e1bce5-df35-41fb-a14d-893847a75a0c)

The two drink dispensers in the bar do not allow themselves to have their maintenance panel opened, nor unbolted with a wrench.
![Dispenser](https://github.com/shiptest-ss13/Shiptest/assets/139566513/0fcdcf4e-fa7d-4227-982a-f1c35286576d)

**Comment by SomeguyManperson** [comment]
The drink dispensers are the fully upgraded variant, which can't be interacted with using tools. The vendor is pixel shifted an entire tile over from where it actually is, which is why it acts odd when moved.
