### ISSUE TITLE
Condiment Packets are invisable and have no name

### ISSUE THREAD

**Issue by Bimbly** [shiptest-ss13/Shiptest#2367]
Issue reported from  Round ID: 1892 (Shiptest)

Reporting client version: 514.1588

Attempted to vend aspartame and hot sauce packets on a boyardee for drink making purposes, stock went down in the vendor but nothing came out.

**Comment by FalloutFalcon** [comment]
This is still a bug.

**Comment by FalloutFalcon** [comment]
It applies to all condiment packs spawning period
