### ISSUE TITLE
[BUG] Malleable Glass not filling

### ISSUE THREAD

**Issue by FalloutFalcon** [shiptest-ss13/Shiptest#2372]
Issue reported from  Round ID: 1899 (Shiptest)

Reporting client version: 514.1589

for some reason the liquid overlay is not working on malleable glass. I will probably find the issue later but in case i forget I am making a issue report.
Buy wireless malleable glass
Look inside
![seewine](https://github.com/shiptest-ss13/Shiptest/assets/86381784/1f503f79-fec1-4cbf-b7d2-dc3abe93ac85)
![lookinside](https://github.com/shiptest-ss13/Shiptest/assets/86381784/7d7d14ff-1fc0-43dd-a0d0-f3e314fcba0c)

**Comment by FalloutFalcon** [comment]
These still dont work
![image](https://github.com/shiptest-ss13/Shiptest/assets/86381784/0feb98b6-1683-4eb2-930c-d0facf3aac4b)
![image](https://github.com/shiptest-ss13/Shiptest/assets/86381784/06ec4b0c-254a-4d77-b73b-ac15cc79a790)

**Comment by PrefabQuasar** [comment]
if its specifically trickwines doing it, they might not have a reagent color. if its any liquid, uh. only pr i can think of that would break this is the one that changed iconstate stuff
either worldstate pr or the older update appearance pr
