### ISSUE TITLE
Moth language is broken and shows ,m when speaking with the prefix

### ISSUE THREAD

**Issue by randyfromrimworld** [shiptest-ss13/Shiptest#2407]
## Reproduction:
Moth language is bugged when using the ,m prefix.
When speaking, the chat menu and the runetext will show ,m in the text, instead of disappearing as it does in other languages.
This does not occur when using the language menu to set a default language.

Example:
*say ,m we need to kill the captain!
Moth says, ",m we need to kill the captain!"
Intended:
*say ,m we need to kill the captain!
Moth says, "We need to kill the captain!"

**Comment by OvercastAngel** [comment]
Seems like the issue is a shared language key. Should be easy enough to fix!
