### ISSUE TITLE
Ghosts can click on containers to open them and make sounds that can be heard by the living

### ISSUE THREAD

**Issue by Zevotech** [shiptest-ss13/Shiptest#2417]
Issue reported from  Round ID: 1950 (Shiptest)

Reporting client version: 514.1589

Ghosts clicking on a container to open it seems to play the sound of the container opening locally to anyone nearby, including other ghosts and living players.

1. Gather circle of ghosts around a leather satchel and spamclick it
2. Realize in horror that people can hear it opening repeatedly
3. Make a bug report like a rational person

**Comment by thestripes** [comment]
![image](https://github.com/shiptest-ss13/Shiptest/assets/115954920/aa9a0a21-0a6f-40e4-b790-531f4fec9f2b)
noted here with the message in question

**Comment by thestripes** [comment]
Another update to this bug report as it falls under the same jurisdiction: ghosts can open boxes and the sound transmits as well
