### ISSUE TITLE
[FEATURE] Add holographic bartenders to Space Diner Ruin

### ISSUE THREAD

**Issue by JukeJukestar** [shiptest-ss13/Shiptest#2447]
## Add holographic bartenders to Space Diner Ruin

![image](https://github.com/shiptest-ss13/Shiptest/assets/76008882/64e102fe-a43d-4276-959f-a3dd6465c96a)

It would be fun for shiptesters to come upon this strange space ruin only to be surprised by a nice drink!
Encourages RP

**Comment by Zevotech** [comment]
As great as it would be, this ruin is pending removal for just being a somewhat ugly box full of food. If you want to bring the idea to fruition, maybe you could remap it into a space bar/diner?
