### ISSUE TITLE
Wrong clothing for artificer

### ISSUE THREAD

**Issue by FalloutFalcon** [shiptest-ss13/Shiptest#2480]
Issue reported from  Round ID: 2003 (Shiptest)

Reporting client version: 514.1589

Correction: This is only an issue if you have alt uniform options enabled

The artificer on the vanquero spawns with the engineer's hazard jumpsuit while we have a specific clothing called the inteq artificer overalls. It even spawns on the ship.
Just gotta go in and replace the outfit.

![image](https://github.com/shiptest-ss13/Shiptest/assets/86381784/ba2fc39c-ea6b-4904-8e50-f34a119978db)
![image](https://github.com/shiptest-ss13/Shiptest/assets/86381784/8d1b2ffb-c68c-4f82-a126-4ed305932ba9)

**Comment by FalloutFalcon** [comment]
![Screenshot from 2023-12-06 07-59-23](https://github.com/shiptest-ss13/Shiptest/assets/86381784/00fa209c-e71f-47cc-a747-fbd2a095d7b5)
![Screenshot from 2023-12-06 07-58-52](https://github.com/shiptest-ss13/Shiptest/assets/86381784/66017032-8b19-4fbc-95c2-2631015d6d97)
So this is just a weird byproduct of alt options
Could be fixed by adding alt_uniform = NULL to the artificer job. A greater issue with alt options in general

**Comment by Apogee-dev** [comment]
Honestly I'd rather alt jumpsuits and suits just be removed entirely from the base outfits. It's an almost completely unused feature and the vast majority of factions don't even have more than one jumpsuit for a given job, nor are they ever likely to.

**Comment by FalloutFalcon** [comment]
> Honestly I'd rather alt jumpsuits and suits just be removed entirely from the base outfits. It's an almost completely unused feature and the vast majority of factions don't even have more than one jumpsuit for a given job, nor are they ever likely to.

I agree
