### ISSUE TITLE
Not enough tools for the vanquero

### ISSUE THREAD

**Issue by FalloutFalcon** [shiptest-ss13/Shiptest#2481]
Issue reported from  Round ID: 2003 (Shiptest)

Reporting client version: 514.1589

The vanquero has two slots for artificers but only 1 pair of gloves and welding googles. I don't know if its meant to be like that.

**Comment by Apogee-dev** [comment]
Vaquero only has one Artificer slot. If there are multiple artificers, the captain has opened up an additional slot. Extra equipment generally isn't provided for slots over the initial count.
