### ISSUE TITLE
Bug with ogre blade/sheath

### ISSUE THREAD

**Issue by DirtTastesBad** [shiptest-ss13/Shiptest#2501]
Issue reported from  Round ID: 2017 (Shiptest)

Reporting client version: 514.1589

Was messing around with the ogre blade and ran into an issue. Clicked on a void tile while doing the stance thing with the sheath. The blade went into my other hand, but it didn't do the dash. It also kept the sheath in the stance position. Every time I tried to dash with it like this, it said that the sheath was empty. But every time I tried to put the blade back in, it said that the sheath was locked.

**Comment by Admiral-Gigaton** [comment]
found this bug too while fucking around on a private server. ogre blade is the nanoforged katananananananana from tot uplink, right? is this the exact same thing, a nerfed version, a different version in general, or something else
