### ISSUE TITLE
Mushroom bowl updateIcon seems broken.

### ISSUE THREAD

**Issue by FalloutFalcon** [shiptest-ss13/Shiptest#2508]
Issue reported from  Round ID: 2020 (Shiptest)

Reporting client version: 514.1589

I poured out the bowl into a different container and the sprite disappeared

Tried this twice

![image](https://github.com/shiptest-ss13/Shiptest/assets/86381784/eec37bc3-8399-469f-9971-16a2aba4d91b)

**Comment by Zevotech** [comment]
i really should rework that entire dmi's sprite handling because it sucks complete ass. might have been caused by #2306
