### ISSUE TITLE
Glaive IDs broken

### ISSUE THREAD

**Issue by FalloutFalcon** [shiptest-ss13/Shiptest#2509]
Issue reported from  Round ID: 2020 (Shiptest)

Reporting client version: 514.1589

It might have been the trick-wine pr but it seems like all of the SRM roles spawn with blank IDs

**Comment by FalloutFalcon** [comment]
The issue is I added a faction in all of the srm jobs in the pre equip but don't call the parent proc. Should be fixed by new glaive ship pr?

**Comment by meemofcourse** [comment]
yeah. will close when #2554 is merged

**Comment by FalloutFalcon** [comment]
Added a comment to make sure no one wasted time resolving the problem
