### ISSUE TITLE
[BUG] Instant Summons Pulls Entire Wall Locker

### ISSUE THREAD

**Issue by TheIssueFairy** [shiptest-ss13/Shiptest#2522]
Issue reported from  Round ID: 2029 (Shiptest)

Reporting client version: 515.1620

Using the Instant Summons spell from the tendril chests moves an entire locker instead of just the marked item within it. I'm pretty sure this isn't intended, as summoning an entire container seems overpowered, but if this is intentional feel free to yell at me.

![shiptest_summonlocker](https://github.com/shiptest-ss13/Shiptest/assets/130010649/2ced04b8-29a0-460e-92ff-10a657375403)

![shiptest_summonlocker2](https://github.com/shiptest-ss13/Shiptest/assets/130010649/ec6c4923-cf5c-49f0-b6c7-04429a4e7f37)

**Comment by SomeguyManperson** [comment]
This behavior is supported by the spell's code, so it's not entirely un-intended

![image](https://github.com/shiptest-ss13/Shiptest/assets/24857008/527af1a8-5099-4644-a1ab-179d9ff0c17e)

**Comment by TheIssueFairy** [comment]
**Closing because I was wrong** and this is an intended function of the spell. I'd say it's still weird (plus it has the unintended effect of moving walllockers which looks silly) but it's not technically a bug.
