### ISSUE TITLE
[BUG] [ADMIN] In-game log viewer cuts off after a while.

### ISSUE THREAD

**Issue by GenericDM** [shiptest-ss13/Shiptest#2546]
The in-game player-specific adminlog viewer cuts off after a while, and stops showing new logs after this point. The logs are still being generated, and can be seen by opening the server logs directly, but this is an inconvenience.

**Comment by goober3** [comment]
this happens because admin logs are linked to local time, for some ungodly reason.

**Comment by GenericDM** [comment]
Should be fixed by #2549
Will reopen if not fixed.
