### ISSUE TITLE
Something is causing absurd amounts of radiation waves to be generated.

### ISSUE THREAD

**Issue by GenericDM** [shiptest-ss13/Shiptest#2645]
Issue reported from  Round ID: 2145 (Shiptest)

Reporting client version: 514.1589

After checking around for lag for a while, I came to the radiation subsystem. It was holding 47,000 radiation waves waiting to be processed, which was causing it to instantly pause itself due to overtiming. I had to use SDQL to delete every radiation wave in existence, at which point the subsystem resumed normal operation.

**Comment by SomeguyManperson** [comment]
Still present?

**Comment by GenericDM** [comment]
> Still present?

Not by the look of things.
