### ISSUE TITLE
[BUG] Access denied text on lockers that are unlocked

### ISSUE THREAD

**Issue by Sweettoothart** [shiptest-ss13/Shiptest#2666]
## Testmerges: [#2446: 'Mining Rework Part 1: First of his Name' by BogCreature at commit b19593b57a](https://github.com/Shiptest-SS13/Shiptest/pull/2446)
[#2513: 'Adds screenless IPCs' by retlaw34 at commit 5f2ff0584c](https://github.com/Shiptest-SS13/Shiptest/pull/2513)
[#2483: 'Auxmos update' by MarkSuckerberg at commit 33adeac8ac](https://github.com/Shiptest-SS13/Shiptest/pull/2483)
[#2581: 'Bunch of Statpanel updates from TG' by MarkSuckerberg at commit f6e60e6cf2](https://github.com/Shiptest-SS13/Shiptest/pull/2581)
[#2488: 'Further mining changes' by thgvr at commit 0971e68ad6](https://github.com/Shiptest-SS13/Shiptest/pull/2488)
[#2618: 'Hunter's Pride' by retlaw34 at commit 4bd1945ff8](https://github.com/Shiptest-SS13/Shiptest/pull/2618)
[#2585: 'Reworks the turbine to be an actual engine' by SapphicOverload at commit 264a9f27d3](https://github.com/Shiptest-SS13/Shiptest/pull/2585)

**Comment by Gorionus** [comment]
Most likely your ID didn't had access requirements to lock the locker

**Comment by Sweettoothart** [comment]
> Most likely your ID didn't had access requirements to lock the locker

Yes, I was a paraclesus patient. However, this still is a issue I believe.

**Comment by FalloutFalcon** [comment]
You cannot lock a locker with the wrong id.
