### ISSUE TITLE
[BUG] Player-built Ion Thrusters Always at 0% Fuel

### ISSUE THREAD

**Issue by Cadunkus** [shiptest-ss13/Shiptest#2671]
## Round ID:
N/A This has occurred over multiple rounds both on official shiptest and replicating it on a private server.

## Testmerges:
IDK

## Reproduction:
Every time I build a new ship thruster the helm console refuses to recognize it as properly fueled. As far as I'm aware it's built and powered correctly (I asked mentors, other players, and the discord but so far I seem to be building it proper) but the ship helm console always says it's 0% powered even after refreshing the helm console, rebuilding the entire thruster, powering it directly, reconnecting, having another player try to use the console, and reconstructing the ship helm console. So far this has only happened with Ion Thrusters (I have yet to attempt it with any other kind.)

![HD-wallpaper-flame-inferno-inferno-flame](https://github.com/shiptest-ss13/Shiptest/assets/140308611/d5239183-c720-4372-a310-9affa859f857)

**Comment by Cadunkus** [comment]
![messy](https://github.com/shiptest-ss13/Shiptest/assets/140308611/73e3f875-302f-47e0-8455-74b593cc8657)
This is basically the entire shuttle. Apparently this should work.

**Comment by SomeguyManperson** [comment]
Only thing I can see that would mess it up would be bad cable positioning, precharger/pacman would have to be missing a knot to fail to connect to eachother

**Comment by RikuTheKiller** [comment]
I can confirm this, any and all player built ion thrusters, regardless of precharger charge level, will fail to be recognized at any power level other than 0%.

**Comment by Hlscientist** [comment]
Tested this in local, seems to be fine; shitty cable placement?

**Comment by SomeguyManperson** [comment]
Can't reproduce
