### ISSUE TITLE
[BUG] "La Creatura" Kepori randomly showing up and vanishing

### ISSUE THREAD

**Issue by Cadunkus** [shiptest-ss13/Shiptest#2678]
## Round ID:

2162

## Reproduction:

In that round a white kepori with no clothes showed up on a jungle planet before diving into the trees and vanishing and then later on my ship. I opened an ahelp ticket and was informed that no admins were goofing around as a white kepori named "la creatura" and stalking me. They also told me to report it as a bug so here I am.

![roundID2162](https://github.com/shiptest-ss13/Shiptest/assets/140308611/b93e6774-622a-46dc-8d80-412a6616d1f1)

**Comment by goober3** [comment]
dude that's so weird

**Comment by TheIssueFairy** [comment]
generic dm

**Comment by Sun-Soaked** [comment]
It cannot be contained. The chains were not enough to hold it. Thanks for the bug report

**Comment by thgvr** [comment]
trolled
