### ISSUE TITLE
Potato Wedges are just considered Potatos

### ISSUE THREAD

**Issue by FelineEsquire** [shiptest-ss13/Shiptest#2693]
## Reproduction:
I think potato wedges are being treated like potatos by the game, as you can cut them into potato wedges again, use them in the loaded potato recipe, and processing them on the cutting board produces tator tots instead of fries, just try to do anything with a potato wedge and you'll see what I mean

**Comment by TheIssueFairy** [comment]
Last I checked, the fry recipe works with the food processor, but not with the cutting board for some reason.
