### ISSUE TITLE
Outpost security section has a bad section of wall.

### ISSUE THREAD

**Issue by Zorazi-Teo-Daedalus** [shiptest-ss13/Shiptest#2707]
Issue reported from  Round ID: 2189 (Shiptest)

Reporting client version: 515.1623

The Outpost security area has a single section of wall that feels like it was missed as an oversight, as the walls to either side are the invincible admin walls, but this one singular one is not.

![image](https://github.com/shiptest-ss13/Shiptest/assets/71111573/515902cd-39dc-48cd-8071-28b19a931a56)

**Comment by goober3** [comment]
vaguely unrelated but there's also a stray shutter in the section of rock beside the outpost brig.
