### ISSUE TITLE
[BUG] Helm Console Failure

### ISSUE THREAD

**Issue by PrefabQuasar** [shiptest-ss13/Shiptest#271]
Issue reported from  Round ID: [212](https://shiptest.ga/stats/rounds/212) (Shiptest)

Reporting client version: 514.1557

## Current Testmerges
#230: '[TEMP] Disable loadout costs' by AsciiSquid at commit a7399a3607
#224: 'Ghetto chem improvements' by PrefabQuasar at commit 8f5da34c09
#251: 'Teshari additions' by MarkSuckerberg at commit d8e5608f0d
#225: 'fix local playsounds falloff' by Cenrus at commit 5b60401440
#218: '[DNM] Swifter's Ship Emporium!' by swifterjack at commit 8e25383e9c
#108: '[MDB IGNORE] Baytiles/the great ship prettyfication' by retlaw34 at commit a7f6eaa4b7
#191: '(Kinda) reworks the black market' by SqueezyS at commit acc3b8081e
#242: 'Adds the Coldridge-Class Corvette' by AtlasRules at commit 72dbfa52c8
#154: 'Disable Events' by ZephyrTFA at commit f821d7d77e
#263: 'The Scrapper' by Omppusolttu at commit 54db1eef77
#260: 'Slime Time: Minor midround slimeperson customization!' by mcmeiler at commit 49a2e1f9ef
#264: 'Boyardee Type B' by retlaw34 at commit 60376e4b28

The helm console on the shetland does not show the overmap, and instead shows a camera centered on the user, navigation controls and velocity indicator are non-functional, issue is probably inconsistent to replicate, since it has been seen earlier, on another ship.

## Replication
As before, replication may be difficult, as the issue seems to occur at random

**Comment by fighterslam** [comment]
Has this happened again or to anyone else? Kinda hard for me to fix the bug if I don't know what's causing it or any circumstances relating to the occurence

**Comment by PrefabQuasar** [comment]
only other time i've seen it was someone posting a screenshot in the discord, it seems to be frustratingly rare and hard to reproduce, sadly

**Comment by PrefabQuasar** [comment]
Ok, I found what it does when it occured again in round recently, still don't know the exact cause, but this bug causes the helm console to become unlinked from the overmap object.

**Comment by MarkSuckerberg** [comment]
Any people see this bug at all lately?
