### ISSUE TITLE
[BUG] Some Wood Tables on Riggs can't be Deconstructed

### ISSUE THREAD

**Issue by untrius** [shiptest-ss13/Shiptest#272]
## Reproduction:
Some of the wooden table on the Riggs class are the wrong type.  This makes it so they can't be deconstructed.  Also when they are destroyed, they do not drop wood.

To solve this, the 4 tables circled in the image below should be changed from /obj/structure/table/wood/bar to /obj/structure/table/wood.

![image](https://user-images.githubusercontent.com/7697956/133908268-04decbcd-0cd0-4d27-a8c2-1c8eda825d7e.png)

**Comment by tiramisuapimancer** [comment]
for the love of god can someone rename these to /obj/structure/table/wood/yeeting or something this happens EVERY time someone maps a bar
