### ISSUE TITLE
[BUG] Anomalies deal toxin damage to otherwise toxin immune races like Plasmamen and IPCs.

### ISSUE THREAD

**Issue by Cadunkus** [shiptest-ss13/Shiptest#2763]
## Reproduction:

The plasmasoul anomaly deals toxin damage to races that should be immune to toxin damage like IPCs and Plasmamen which is especially bad since as far as I know you can't heal said toxin damage when that happens.

(also there appears to be another bug where when you ahelp it to hopefully get rid of the permanent 90 damage on your character you get the response "github" and then the ticket immediately closes with no further explanation which is very unhelpful.)

**Comment by TheIssueFairy** [comment]
IPCs can be healed from toxin damage with system cleaner (made using chemistry), I'm not sure how it works for plasmamen.
