### ISSUE TITLE
[BUG] Syringes can't change transfer amounts

### ISSUE THREAD

**Issue by RikuTheKiller** [shiptest-ss13/Shiptest#2794]
Syringes can't change transfer amounts, even though codewise there's support for it.

Syringe push/pull is also very clunky compared to the more modern LMB/RMB instead of activation.

Recommended solution is to just switch push/pull to LMB/RMB like /tg/station did while keeping unit change on activation.

## Reproduction:

Try to swap the transfer amount of a syringe by activating it. It won't work, rather toggling push/pull.

**Comment by FalloutFalcon** [comment]
We would have to port TGs entire intent system.
