### ISSUE TITLE
[BUG] Active mines can be picked up by trash bags

### ISSUE THREAD

**Issue by Hlscientist** [shiptest-ss13/Shiptest#2813]
## Round ID: 
2254

## Testmerges: 
https://github.com/shiptest-ss13/Shiptest/pull/2759

## Reproduction:
 Use trash bag upon active landmines, land mine will appear in garbage bag. (pretty simple)

**Comment by Sun-Soaked** [comment]
fixed in [pr](https://github.com/shiptest-ss13/Shiptest/pull/2759), storage items now have a check to prevent picking up anchored objects

**Comment by Galdar02** [comment]
lol, lmao
