### ISSUE TITLE
[BUG] Social anxiety trait checks for radio me's even though it shouldnt

### ISSUE THREAD

**Issue by Hlscientist** [shiptest-ss13/Shiptest#2893]
## Round ID:
 2329

## Testmerges:
 N/A, bug should not be caused by any active TMs

## Reproduction:
1 - Have social anxiety trait
2 - have social anxiety
3 - attempt to radio me ( ; beeps*)
4 - cry as the moment is ruined as you have social anxiety and the radio me does not go through

**Comment by FalloutFalcon** [comment]
I cant reproduce this. I think its related to eye contact which is annoying to replicate on local host by myself

**Comment by FalloutFalcon** [comment]
fixed in #3222
