### ISSUE TITLE
[FEATURE] Cybernetic Stomachs (or a way to fix stomachs)

### ISSUE THREAD

**Issue by terg-but-ius** [shiptest-ss13/Shiptest#292]
## Name of feature: 
Cybernetic Stomachs (or a way to fix stomachs)

### Additional Info:
Because for some reason there isn't a cybernetic organ for that nor a surgery and that makes it so if you don't have a fresh monkey/legion corpse on hand you can't fully fix a body whose organs have decayed and that makes me ANGRY.

**Comment by Anderson-Cooper** [comment]
Yea i could *maybe* do that when i get access to a proper computer.
