### ISSUE TITLE
[BUG] Mining borg can't fit three PKA cooldown mods

### ISSUE THREAD

**Issue by williamcll** [shiptest-ss13/Shiptest#2921]
## Reproduction:

The Cyborg PKA cooldown decrease module has a capacity of 30. which means you can fit 3 and still have 10% left. However when I was playing as a mining borg the engineering could not put a third on me, stating that there's only 20% space left. Of note I also have cyborg repair installed.

**Comment by SomeguyManperson** [comment]
The cybirg kinetic accelerator only has 80 capacity

**Comment by williamcll** [comment]
> The cybirg kinetic accelerator only has 80 capacity

wow that sucks, when was this change made?

**Comment by thgvr** [comment]
been like that for years on tg
