### ISSUE TITLE
[FEATURE] IPC Expansion

### ISSUE THREAD

**Issue by Mannybrado** [shiptest-ss13/Shiptest#294]
## Name of feature: IPC Expansion. Make them cool :)

Ideasguy time.
My general idea for IPCs is that they should be significantly more versatile throughout the round for a specific form of labor at a time, while never being a very good jack-of-all trades.(humans are that :) )
Effectively, IPCs would have actual utility and abilities similar to a cyborg but without the limitations and some of the power stripped. IPCs should be more about customization and modularization, as installing upgrades for an IPC to fit with a "build" would way better than... now. As of right now, the only upgrade they can receive is the ability to eat.(i think?) Kind of boring. 
Anyways, lets begin.

### **Chassis**
What does IPC stand for? That's right. Integrated Positronic _Chassis_, so why not add some actual variety (OR GAMEPLAY) there? The basic rules go as follows: 
Every chassis model has plus-sides and weaknesses, as well as some having unique abilities based on their manufacturer. Also to note, every chassis model would be able to store different types and amounts of modules, which I will get to later. Now, starting from the top:
(i dont actually know how damage mods within species work, and i dont know if its even possible to have it be seperate within a species, however i am an ideasguy and thus im not going to hurt my small brain thinking about it and just will use the modification values i found in the code)

**- ALL IPC BONUSES, WEAKNESSES AND STATS**
 * All IPCs run on power, functioning exactly the same as they do now, with the power plug.
 * Almost all IPCs are subsequently incredibly weak to EMPs. 
 * All IPCs are immune to radiation.
 * IPCs cannot wear hardsuits. (they dont fit, their sensors dont work through the suit, etc) They can, however, wear normal space-suits.
 * Almost all IPCs are slightly more resistant to zero-pressure environments. 
 * Almost all IPCs are weak to burn and heat damage of varying degree.
 * IPCs do not need to breathe.
 * IPCs do not metabolize chems. (cant inject them anyways)
 * IPCs can only be healed through specific means. (welder, wire, etc)
Assume the mod changes for all chassis are this unless otherwise stated:
 burnmod: 1.75
 heatmod: 1.5
 brutemod: 0.9
 punchdamagelow: 5
 
**- Morpheus Cyberkinetics Chassis**
The "baseline model", this one is the most similar to the current IPCs in function. They are the most modular and have the greatest potential for upgrades, however they have no unique function or abilities.
 * Can accept modules of all sizes. 
 * Can accept up to 8 modules.

**- Bishop Cyberkinetics Chassis 1.0, Ward-Takahashi Manufacturing Chassis**
The first of three medical chassis, this one is designed as a general side-grade to the baseline. They aren't as modular and are a bit weaker, however they are slightly faster. 
 * Can only accept module size 1 and 2. (small, medium, basic, advanced, etc, idk, thats why im using numbers)
 * Can accept up to 6 modules.
 burnmod: 1.85
 brutemod: 0.95
 speedmod: 0.15 (slightly faster!)

**- Bishop Cyberkinetics Chassis 2.0**
The heavy version of the original, this chassis is meant for EVA rescue missions. Not super modular due to the special features present, though of all of the chassis capable of space-walking, this one is the weakest, but fastest and most modular.
* Can only accept module size 1 and 2.
* Can accept up to 4 modules.
* Cannot wear armor or helmets.
* Can survive in zero-pressure environments.
 armor: 10
 burnmod: 1.8
 speedmod: -0.2 (slightly slower!)
 
**- Hephaestus Industries Chassis 1.0**
The "medium" combat chassis, sports increased armor at the cost of a small amount of speed. Fairly modular. Sports weak EMP protection.
* Can only accept modules size 1 and 2.
* Can accept up to 6 modules.
* Very weak EMP protection.
 armor: 20
 speedmod: -0.1
 
**- Hephaestus Industries Chassis 2.0**
 The "heavy" combat chassis, sports greatly increased armor at the cost of a lot of speed. Not very modular. Sports weak EMP protection, can space walk, and packs a punch.
* Can only accept module sizes 1 and 2. (literally not enough space for any more)
* Can only accept 2 modules.
* Very weak EMP protection.
* Cannot wear armor or helmets.
* Can survive in zero-pressure environments.
armor: 50
burnmod: 1.65
speedmod: -0.65
punchdamagelow: 10
punchdamagehigh: 25

**- Xion Manufacturing Group 1.0** 
 The first-in-line, multi-purpose cargo-engineering chassis. Sports increased heat and pressure resistance at the cost of a teeny amount of speed. Includes a big storage implant and integrated welding goggles.
 * Can only accept module sizes 1 and 2. 
 * Can accept up to 4 modules.
 * Increased pressure resistance from normal.
 * Includes big storage implant.
 * Includes integrated welding goggles.
 burnmod: 1.6
 heatmod: 1.25
 speedmod: -0.1
 
 **- Xion Manufacturing Group 2.0**
  The ultimate engineering chassis. Has great-super-awesomely increased heat resistance, can survive in zero-pressure environments, has some armor, but is very slow. Sports weak EMP protection, a big storage implant, a toolbelt implant, and integrated welding goggles.
  * Can only accept module sizes 1 and 2.
  * Can only accept 2 modules. 
  * Cannot wear armor or helmets.
  * Weak EMP protection.
  * Includes big storage implant.
  * Includes toolbelt implant.
  * Includes integrated welding goggles.
  armor: 20
  burnmod: 0.9(!!!!!)
  heatmod: 0.9
  speedmod: -0.65
  punchdamagelow: 10
  punchdamagehigh: 15

 **- Shellguard Munitions [V2](https://www.youtube.com/watch?v=dYpYQHb-ZKg&t=1561s) Chassis**
 The "light" combat chassis, sports greatly increased speed, some armor, and some heat protection at the cost of all modularity. Sports decent EMP protection. 
 * Cannot accept any modules.
 * Decent EMP protection.
 * Cannot wear armor or helmets.
 armor: 15
 burnmod: 1.5
 heatmod: 1.3
 speedmod: 0.8
 punchdamagelow: 10
 punchdamagehigh: 15

**- Zeng-Hu Pharmaceuticals Chassis**
The ultimate medical chassis. Very light and speedy, includes a big storage implant, a night-vision medical hud, an on-board upgraded defibrillator that drains from the IPC's battery, a surgery tool implant and finally, total EMP immunity. Very fragile.
* Cannot accept any modules.
* EMP immunity.
* Includes NVG MedHud.
* Includes unique integrated upgraded defibrillator.
* Includes surgery tool implant.
* Includes a big storage implant.
burnmod: 2
heatmod: 1.55
brutemod: 1
speedmod: 0.3

I couldn't think of more. Well, I could, but this gets the idea across fine.

**###MODULES** 
Modules are upgrades for IPCs that can be acquired through research and (hopefully)exploration. They enhance or add new abilities to IPCs, some introducing new abilites and debuffs, while others are just straight upgrades. Each module falls under a size group, where you can put as many modules in that your chassis allows until the size cap is reached. For example, if my chassis has a max of 4 modules, I could fit four(4) one(1) size modules within MYSELF, and so on.
Modules can be swapped or added using surgery, or by using a RIPCED. Oh yeah.

**Module Size 1**

**- Integrated Flashlight.** Drains small amounts of power while active. Can be upgraded with another module point to unlock a more powerful mode that drains medium amounts of power while having the effectiveness of a spotlight.
**- Armor Plate.** Adds 5 armor to your chassis. Can take 2 of them. Decreases speed by 0.05 when used.
**- Integrated Welding Goggles.** Welding goggles. Yep.
ETC.

**Module Size 2** 

**- HUD Implant.** All of them except the NVG ones or whatever. Obviously, separate.
**- Small Storage Implant.** Gives you, the, uh, storage implant. 
**- GUN FINGERS.** Activate the ability then click to be able to shoot 5 relatively weak bullets out of your hand. Does small damage to the arm that has the implant when fired.
**- Surgery, Toolbelt, etc Implants.**
**- Integrated Welding Tool w/ small tank.**
ETC.

** Module Size 4**
**- Jetpack.** Drains power when used.
**- Flame-Thrower.** Oh yeah...,,,.,.,
**- Portable Teleporter.** Functions like teleporter array but you can deploy a portal anywhere.
**- Automatic Research Surveyor.** The best thing ever, I think
ETC.
Perhaps there could be more, I.E. types of limbs and such.
Upgrades to internal parts of IPCs could be explored and should, but i dont want to write anymore 😭 
### Additional Info: 
share your ideas or things you think i should change
numbers aren't really accurate

**Comment by TerryTehCoder** [comment]
This is really cool. But IPC code is very yucky(and hard to read), and it'd definitely take a lot of balancing if it is implemented.
