### ISSUE TITLE
[FEATURE] THE GREAT RETURN OF THE LIEUTENANT

### ISSUE THREAD

**Issue by HighPrincessErinys** [shiptest-ss13/Shiptest#304]
## Name of feature: 
LIEUTENANTS BACK BAYBEE

### Related Pull Request on other codebase: 
https://github.com/Whitesands13/Whitesands/pull/544 THE LIEUTENANT KILLER

### Additional Info:
So, people have discussed before making the Head of Personnel act as a Comms Officer, or be the First Officer, or other such things, for Shiptest. HOWEVER. I RAISE YOU, THE FORGOTTEN, REDHEADED STEPCHILD FROM HISTORY PAST. THE LIEUTENANT.
REPLACED IN FAVOR OF THE SOLGOV REP IN THE LINKED PR, WE CAN USE THE DIFFS TO *RESURRECT* THE LIEUTENANT, WHO IS AN ACTUAL LITERAL PERFECT FIT FOR SHIPTEST, AND FINALLY GIVE OUR FORGOTTEN LAD SOME LOVE.

BRING HIM BACK!!!

**Comment by zestybastard** [comment]
what does lieutenant actually do that HoP doesnt already do (namely being the captain but cooler)

**Comment by rye-rice** [comment]
well they are even more cooler and more thematically appropriate

**Comment by Nobelium-XVIII** [comment]
spiffy uniform
no nagging ~~wife~~ dog

**Comment by HighPrincessErinys** [comment]
> what does lieutenant actually do that HoP doesnt already do (namely being the captain but cooler)

they had a cool energy revolver which had snares too and it was cool

**Comment by triplezeta** [comment]
why is this an open issue
