### ISSUE TITLE
Toggle Deadchat is not working.

### ISSUE THREAD

**Issue by fighterslam** [shiptest-ss13/Shiptest#3073]
Issue reported from  Round ID: 2436 (Shiptest)

Reporting client version: 515.1639

Toggle-Dead-OOC verb does not actually disable Dchat, just leaves an admin log.

**Comment by generalthrax** [comment]
This verb specifically disallows dead mobs to speak in _OOC_. They can still speak in deadchat. As for if it works, it does.
![wawa](https://github.com/shiptest-ss13/Shiptest/assets/139387950/a9f16bf3-1e0c-451a-a0af-ce02aebe13c2)
This is probably good to close. If you would like to limit a player's access to dead chat, all we have at present is Deadchat mutes.
