### ISSUE TITLE
[BUG] At least one drink fails to get a sprite when mixed in a glass, then fails to revert back

### ISSUE THREAD

**Issue by thestripes** [shiptest-ss13/Shiptest#3132]
## Reproduction:

1. Mix a mixed drink, specifically in this bug, the Tadrixx Float.
2. Pour into a drinking glass.
3. The glass becomes invisible, and on turf menu and right click it shows every single drink sprite on the .dmi.
4. Drink it, placing it back down to reveal that the glass isn't reverting back into being a generic glass.

**Comment by generalthrax** [comment]
After checking I noticed that the Tadrixx Float was using an icon called "tadrixxfloat" that didnt exist. I'll fix this in like 2
