### ISSUE TITLE
[BUG] IDs must be removed and reinserted into wallets after spawning to work properly

### ISSUE THREAD

**Issue by Anticept** [shiptest-ss13/Shiptest#3137]
Basically, ID cards wont trigger access or display jobs to other people until this is done. Bug from https://github.com/shiptest-ss13/Shiptest/pull/2979

[Round ID]: 2473

## Testmerges:

[#2848: 'Mob Spawner Rework' by FalloutFalcon at commit bc3882944f](https://github.com/Shiptest-SS13/Shiptest/pull/2848)
[#2982: 'Ports Bodycameras from Fulp' by Zevotech at commit 18e909ba25](https://github.com/Shiptest-SS13/Shiptest/pull/2982)
[#3112: 'The SUNS Panacea-class Infirm Vessel' by Latentish at commit f34884499d](https://github.com/Shiptest-SS13/Shiptest/pull/3112)
[#3094: 'tweaks to recoil and spread' by FalloutFalcon at commit 071f32bb9c](https://github.com/Shiptest-SS13/Shiptest/pull/3094)
[#3080: 'Ports 'Command bar typing indicators (client side html version)'' by Skies-Of-Blue at commit 0d27d7d321](https://github.com/Shiptest-SS13/Shiptest/pull/3080)
[#3067: 'SSD Indicators Will Be Real In 2020' by Skies-Of-Blue at commit 5397dd493a](https://github.com/Shiptest-SS13/Shiptest/pull/3067)
[#2835: 'Cybersun's blacksite ruin' by Marabout2 at commit ccc2e85fbb](https://github.com/Shiptest-SS13/Shiptest/pull/2835)

## Reproduction:

Spawn in, try to open a door or examine someone who hasn't reinserted ID yet.

**Comment by FalloutFalcon** [comment]
oops. dunno how this wasn't caught durning its many test merges. The you prob just need to refresh the wallet once you add the id should be a simple fix.

**Comment by Anticept** [comment]
Not sure if it's related but every creature without an ID touching a door is also causing a runtime, it's trying to retrieve an ID that does not exist on the mob.

**Comment by Mirag1993** [comment]
need an update method in the combined access variable in the wallet
