### ISSUE TITLE
AI cores are able to be moved despite being bolted down.

### ISSUE THREAD

**Issue by Joel-682** [shiptest-ss13/Shiptest#3161]
Issue reported from  Round ID: 2490 (Shiptest)

Reporting client version: 515.1630

Steps to reproduce:
1. Spawn as AI (Or become an AI through core installment)
2. Get a carbon or metallic lifeform to walk into you on help intent
3. Check your floor bolts
4. They're on, oh no. Despair. 

I didn't test with pulling, nor can I, as I'm the AI. But walking into the core with help intent seems to do the trick when it shouldn't.

**Comment by Martinpachu** [comment]
so true. i was the catboy.

**Comment by generalthrax** [comment]
On testing on local, this seems to be working as intended. You do _start_ anchored, so I could see some confusion stemming from the fact you toggled floor bolts thinking you'd be anchored. Foxgirl for scale (I am attempting to walk into it on help intent to no success and pull it as intended)
![waw](https://github.com/shiptest-ss13/Shiptest/assets/139387950/de0c5c61-23ea-4709-8bd9-75948441d65a)

**Comment by Joel-682** [comment]
I am 99% sure that I was bolted, because I unbolted, bolted again, and was still moveable. 

Time to test the Delta with Martin to see if I find it again, until then, I'll close this since it can't be reproduced.

**Comment by Anticept** [comment]
I can confirm that this is an issue, I just haven't been able to consistently reproduce. Sometimes you can move a bolted core, sometimes you can't.
