### ISSUE TITLE
[FEATURE] Ghost role rework

### ISSUE THREAD

**Issue by rye-rice** [shiptest-ss13/Shiptest#320]
## Name of feature:
Make ghost roles work better with how shiptests are run

### Additional Info:
So the purpose of ghost roles are to get players back in the round in a fun way after they have died, or for players to kill time after they have died. However, some ghost roles have a completely unique and fun gameplay loop that's a nice change of pace from the normal station gameplay loop, while still opening the opportunity to interact with them.

The same is true for shiptest, however it works a little worse. Since ruins only load when a planet is visited, its usually free loot since theres no ghost roles using the loot/ no ghost roles defending the loot, and those who do play are immediatley interacted with by the ship crew that landed there.

So what i'm thinking of is something like this:
Replace the ghost role button for ghosts with a 'lobby' button
It opens up a lobby menu similar to TG's mafia lobby system, where a random ghost role is picked and ghosts can ready up
If enough players ready up for the same ghost role, it will load the appropiate planet, load it on the overmap or choose a existing planet on the overmap, then spawn them all in at the same time. Any empty slots can be joined later like it used to be.

**Comment by Anderson-Cooper** [comment]
Or maybe you could port CTF from TG, and add those as "Skeleton ships" that have sustained heavy damage and require extensive repair. When I can start coding, I will try to port CTF and hopefully make skeleton ships
