### ISSUE TITLE
[BUG] Pill Sprites Missing in ChemMaster 3000

### ISSUE THREAD

**Issue by TheIssueFairy** [shiptest-ss13/Shiptest#3208]
Issue reported from  Round ID: 2527 (Shiptest)
Reporting client version: 515.1641

1. Open ChemMaster
2. ???
![image](https://github.com/user-attachments/assets/2c615d79-212a-4fbb-bda3-94d60e37badd)

I'm kind of wondering if this is just on my side or not.

**Comment by thgvr** [comment]
CDN is having issues, technically not a code bug

**Comment by TheIssueFairy** [comment]
> CDN is having issues, technically not a code bug

Should I close this, then?

**Comment by TheIssueFairy** [comment]
Closing it.
