### ISSUE TITLE
[BUG] Revolver with six 200 brute projectiles (Execution)

### ISSUE THREAD

**Issue by generalthrax** [shiptest-ss13/Shiptest#3252]
## Round ID:

Happened in a local and on auth.

## Testmerges:

Highly unlikely to be tied to any current testmerges

## Reproduction:

1. Attempt to execute someone with the targeting mouth interaction
2. Fail
3. Watch it cycle again
4. Fail again
5. Repeat a few times, for all six bullets in a revolver
6. Fanfire into six people
7. Kill them all instantly with one shot, 200 brute

Strangely seems to be tied to the next bullet to be fired from a magazine. You can unload the bullet and put it into an entirely separate gun and it'll also do that same damage.

Probably can happen with any gun. I tested a Himehabu, a Flaming Arrow, a Shadow, and a Pistole C.

**Comment by firebudgy** [comment]
![image](https://github.com/user-attachments/assets/6a657dd4-afca-4c58-91bf-05d8f2871c4c)
![image](https://github.com/user-attachments/assets/8b72224a-16c7-4648-8d63-8d8abf84ae78)
