### ISSUE TITLE
.45 HP description reads as 10mm HP

### ISSUE THREAD

**Issue by dessysalta** [shiptest-ss13/Shiptest#3271]
Issue reported from  Round ID: 2580 (Shiptest)

Reporting client version: 515.1634

Go to the cargo tab of the outpost console and type "10mm". .45 HP shows up for some reason. Cost me five hundred credits. Greedy bastards...

**Comment by FalloutFalcon** [comment]
typo! 
![image](https://github.com/user-attachments/assets/e58b0790-2b0c-483d-a6b6-499df2585804)
