### ISSUE TITLE
[BUG] One frontiersmen mob drops an "i demand" revolver.

### ISSUE THREAD

**Issue by Sadhorizon** [shiptest-ss13/Shiptest#3297]
## Round ID:
2615

## Testmerges:
#3238 might be causing this. That or it's an issue from when they were added.

## Reproduction:
![obraz](https://github.com/user-attachments/assets/25c3d7f6-caac-4507-9116-1997cdc097f6)

Kill one of the mobs, idk which one is this.

**Comment by goober3** [comment]
I DEMAND!!! THAT "apogee-dev" to be DEMOTED!!! it was the best experience being neutral wizard and being the ones who rescue you in a different methods and everyone saying "what the fuck? are you a terrorist?" then replying "we're the good wizard we are the hero in this story"
