### ISSUE TITLE
[BUG] Being Cloned Causes Removable Colorblindness

### ISSUE THREAD

**Issue by untrius** [shiptest-ss13/Shiptest#331]
Copy of https://github.com/Whitesands13/Whitesands/issues/561

## Reproduction:
1) Build a complete cloning setup
2) Get scanned
3) Die
4) Get cloned (or drag your aghost into an empty clone)
5) Be colorblind

Workaround:
Equipping and removing a welding helmet removes this colorblindness

**Comment by TheNeoGamer42** [comment]
this can also happen with aheals, and I think sometimes even being healed out of crit.

**Comment by tiramisuapimancer** [comment]
Likely related to the tgcode-recent "being blind also makes you colorblind because the rough circle of visible area around blind characters is technically them feeling around" and sleeping making you blind (examining sleeping people with Empath reads them as blind)
