### ISSUE TITLE
[BUG] Spacepod Charge, Integrity, and Velocity Missing from Status Tab

### ISSUE THREAD

**Issue by untrius** [shiptest-ss13/Shiptest#334]
Copy of https://github.com/Whitesands13/Whitesands/issues/553

## Reproduction:
1) Construct spacepod
2) Enter spacepod
3) Charge, integrity, and velocity are not in status tab

**Comment by Ms-Mee** [comment]
Also got fucky atmos, a missing verb etc. etc. pods are fucky as fuck
