### ISSUE TITLE
[BUG] Trying to construct a reinforced wall creates a turf/closed instead of /turf/closed/wall/r_wall.

### ISSUE THREAD

**Issue by DrCrawler** [shiptest-ss13/Shiptest#3396]
## Round ID:
2695 (if i remember correctly)

## Testmerges:

#3285 
#3351
#3291 
#3361 
#3146 
#3343 

## Reproduction:

Try to build a reinforced wall.
![image](https://github.com/user-attachments/assets/4ccb19ac-4dd5-4e1e-ab09-6a58719b74da)

**Comment by FalloutFalcon** [comment]
#3146

**Comment by FalloutFalcon** [comment]
fixed in #3146
