### ISSUE TITLE
Hallucination Anomalies give you infinitely increasing negative hallucination value

### ISSUE THREAD

**Issue by generalthrax** [shiptest-ss13/Shiptest#3435]
Issue reported from  Round ID: 2704

Reporting client version: 515.1641

Go to a hallucination anomaly and get affected by it. You'll have negative hallucination value in vv, and it'll keep increasing forever and never go away. Highest I've seen is probably -16000

Have to keep setting peoples hallucination to 0 in vv

**Comment by Zevotech** [comment]
This happens for most anything that causes a hallucination. Mainly had it happen with BZ inhalation.

**Comment by Anticept** [comment]
Sounds like hallucinations needs to get a refactor to cap it. I know there have been malfunctions with RDS too that cloudy fixed at one point.
