### ISSUE TITLE
[BUG] Throw_range only goes halfway

### ISSUE THREAD

**Issue by generalthrax** [shiptest-ss13/Shiptest#3487]
# Reproduction:

On items that have throw_range (hand grenades, knives, spears), they'll have a throw range of, say, 6 or 8 or something. In practice, it'll be more like 3 and 4.

>Spawn a weapon intending to be thrown
>Check its throw range
>Throw it
>Notice it only goes halfway

This is probably not intended and I'm not really sure whats wrong

**Comment by MarkSuckerberg** [comment]
fixed in #3522
