### ISSUE TITLE
[BUG] shuttles on ruins spawned in via dynamic encounters do NOT spawn

### ISSUE THREAD

**Issue by triplezeta** [shiptest-ss13/Shiptest#36]
## Reproduction:

blacklist EVERY ruin except caravan ambush (not all of the ruins are on the blacklist by default btw :))))

go to a weak energy signal

all of the functional shuttles will be completely missing

**Comment by MarkSuckerberg** [comment]
Fixed by #42

**Comment by triplezeta** [comment]
MARK WAIT NO IT WASNT FIXED NOOOO
