### ISSUE TITLE
No more watermelon slices

### ISSUE THREAD

**Issue by Cenrus** [shiptest-ss13/Shiptest#360]
1. cut watermelon with sharp object like hatchet
2. it produce seeds, not invidual slices

**Comment by TheNeoGamer42** [comment]
This issue happens to onions too I think, and probably all other things that can be sliced up

**Comment by Moltovz** [comment]
That's fucking hilarious. I'll look into it unless someone fixes it before I get to it.

**Comment by Ms-Mee** [comment]
I FORGOR
My fault, didn't add a check for the sliceables for ghetto seed extraction.
Unless those were never a thing but probably were

**Comment by Ms-Mee** [comment]
#297 My second PR and already fucked something up, basedcoding
