### ISSUE TITLE
The roundstart shiptest is broke as fuck?

### ISSUE THREAD

**Issue by TheNeoGamer42** [shiptest-ss13/Shiptest#364]
Issue reported from  Round ID: [296](https://shiptest.ga/stats/rounds/296) (Shiptest)

Reporting client version: 514.1557

![image](https://user-images.githubusercontent.com/58159167/137853934-652c20a4-9f93-4792-b403-48a2fa69eb45.png)
what

also I spawned a different ship and it wasnt fucked like this, also the roundstart one was a riggs class

**Comment by triplezeta** [comment]
issue observed here identical to the issue in #271. that being said this is a very interesting lead.

**Comment by untrius** [comment]
This happened to me on Round 331.  It was a Riggs-Class, but not the round-start one.  It happened after launching and landing 20+ times.

![image](https://user-images.githubusercontent.com/7697956/139539143-6a4aeeca-48db-4428-8a9b-9f0c3960f0dd.png)

**Comment by untrius** [comment]
15ish minutes later, all the walls and turfs on my ship qdel-ed...  I have no idea if this is related.

![image](https://user-images.githubusercontent.com/7697956/139539745-0e60b717-aa39-48b1-84bb-3df9c6674bc9.png)

**Comment by tiramisuapimancer** [comment]
Formally, this bug is called slimegirl trafficking

> 
> 
> 15ish minutes later, all the walls and turfs on my ship qdel-ed... I have no idea if this is related.
> 
> ![image](https://user-images.githubusercontent.com/7697956/139539745-0e60b717-aa39-48b1-84bb-3df9c6674bc9.png)

**Comment by untrius** [comment]
The removal of the floors and walls seems to have happened as another ship was docking at the same location.

**Comment by TheNeoGamer42** [comment]
probably relevant runtime log 
![image](https://user-images.githubusercontent.com/58159167/139540597-696276cc-309e-4cbc-9d69-b6a671f9b776.png)
