### ISSUE TITLE
[FEATURE] HOLY SHIT GOD PLEASE NEW ROUNDSTART SHIP ROTATION

### ISSUE THREAD

**Issue by HighPrincessErinys** [shiptest-ss13/Shiptest#366]
## Name of feature:
AAAAAAAAAAAAAAAAAAAA

### Related Pull Request on other codebase:
FICJHG

I AM SICK AND TIRED OF THE SAME 5 SHIPS EVERY VOTE ITS LIKE ALWAYS THE SHETTY OR THE RIGGS TOO PLEASE BREATHE SPICE INTO THE LIFE OF THE PEOPLE WHO JOIN UP ON THE ROUNDSTART SHIP

**Comment by triplezeta** [comment]
the roundstart ship is intended to be a reliable generalist for new people unable to afford their own ships. people who want to play something else can easily ask for cointests.

**Comment by rye-rice** [comment]
roundstart starfury :trollface:
