### ISSUE TITLE
[BUG] PGF Elated Bolide Class Assault Lander

### ISSUE THREAD

**Issue by Overteh** [shiptest-ss13/Shiptest#3688]
## Round ID:
localhost

## Testmerges:
none

## Reproduction:
Download latest PGF Elated Bolide Class Assault Lander and see:
Excess airlock at kitchen
![image](https://github.com/user-attachments/assets/f2fc2ce8-d061-418e-92bf-8082bd0cf60b)
Overflowing closet at armory
![image](https://github.com/user-attachments/assets/a95b30f3-668c-405c-bb14-1ec261b3f787)

**Comment by meemofcourse** [comment]
the way this issue is titled makes it seem like the bolide is the bug
