### ISSUE TITLE
[FEATURE] capybara

### ISSUE THREAD

**Issue by HighPrincessErinys** [shiptest-ss13/Shiptest#377]
## Name of feature:
capybaras!! on jungleplanets!!

### Related Pull Request on other codebase:
https://github.com/vgstation-coders/vgstation13/pull/28618

### Additional Info:
hello please add capybaras and put them on jungleplanets jungleplanets could probably use some mobs. like capybaras!! or monkeys i guess if you're super lame

**Comment by PetMudstone** [comment]
You can't just add capybaras and not post pictures you monster

**Comment by HighPrincessErinys** [comment]
> You can't just add capybaras and not post pictures you monster

sir this is a feature request

**Comment by PetMudstone** [comment]
wait shoot i'm an idiot. Regardless relevant images of capybaras from the linked PR.
![CAPY](https://user-images.githubusercontent.com/9782036/104997534-59962500-59ef-11eb-9a60-c19e509bda8a.png)
