### ISSUE TITLE
[BUG]the NT-LS-1013 has no sprite

### ISSUE THREAD

**Issue by Ratvarr** [shiptest-ss13/Shiptest#3790]
## Round ID: 
2867

## Testmerges:
[#3753: '[DNM] ports Bungalow-13#204 "You can stand in sofcrit, but not for long before colapsing if you take more damage" ' by rye-rice at commit a36a24f9b9](https://github.com/Shiptest-SS13/Shiptest/pull/3753)
[#3764: 'Auxmos update and potential fix (DO NOT MERGE)' by MarkSuckerberg at commit abb0e4e609](https://github.com/Shiptest-SS13/Shiptest/pull/3764)
[#3323: 'Remaps the Kansatsu-class Scout Courier.' by Sadhorizon at commit 69391c7f49](https://github.com/Shiptest-SS13/Shiptest/pull/3323)
[#3730: 'Gun Tweaks' by Erikafox at commit 967ca9f321](https://github.com/Shiptest-SS13/Shiptest/pull/3730)
[#3375: 'Moves the Brazillab ruin to Sandplanet and fixes the Trabuco's inhand sprites' by Zevotech at commit 34037fd165](https://github.com/Shiptest-SS13/Shiptest/pull/3375)
[#3512: 'Attempts to Fix Temperature + Makes It More Realistic in the Face of Extreme Temperatures' by rye-rice at commit 6b1056455e](https://github.com/Shiptest-SS13/Shiptest/pull/3512)
[#3694: 'Ammo Antics' by Erikafox at commit 5745544395](https://github.com/Shiptest-SS13/Shiptest/pull/3694)
[#3693: 'Replaces the Hyena with the Derecho' by Apogee-dev at commit 411423645f](https://github.com/Shiptest-SS13/Shiptest/pull/3693)
[#3711: 'Succumb Code Touchup' by MarkSuckerberg at commit d668253c64](https://github.com/Shiptest-SS13/Shiptest/pull/3711)
[#3519: 'Electric Welder & Cell Component' by thgvr at commit 58e05f3731](https://github.com/Shiptest-SS13/Shiptest/pull/3519)
[#3016: 'Tegu-class Communications Freighter' by goober3 at commit b808ed78b9](https://github.com/Shiptest-SS13/Shiptest/pull/3016)
[#3758: 'Factional Cargo, done in a day' by rye-rice at commit 7841d118ee](https://github.com/Shiptest-SS13/Shiptest/pull/3758)

## Reproduction:
Find an NT-LS-1013. 
It has no sprite.
Or inhand.

**Comment by Erikafox** [comment]
yeah that's a pretty old snowflaked item i think it just needs to be actually subtyped or swapped out for something.
