### ISSUE TITLE
[BUG] Syndicate Sleepers cannot be controlled from inside

### ISSUE THREAD

**Issue by Sun-Soaked** [shiptest-ss13/Shiptest#388]
The Syndicate Sleeper has a "controls_inside" variable that's supposed to give it the ability to be used from inside, for self-healing purposes.
The code that controls how this var functions is here, under sleeper.dm:
![code](https://user-images.githubusercontent.com/45698967/139070995-d7e78ac6-2e76-41f0-bd33-40abe6522f79.PNG)
But it seems to be completely nonfunctional at the moment, likely related to whitesand's sleeper rework.

## Round ID:
n/a

## Reproduction:
Locate syndicate sleeper. Climb inside and watch the control ui disappear. Cry.

**Comment by Bokkiewokkie** [comment]
Old ass topic proc for a machine with TGUI moment
