### ISSUE TITLE
[BUG] You can go to different ships in hyperspace

### ISSUE THREAD

**Issue by TheNeoGamer42** [shiptest-ss13/Shiptest#390]
## Reproduction:
For the longest time we haven't really considered this, but, theres literally nothing separating ships except Very Deadly Hyperspace and space tiles in between. We should probably put the walls we use for planets and such around ships to prevent fuckery such as going to different ships, as someone has finally done that and proven its possible with an amount of time, 2 people, and chems.

**Comment by Ms-Mee** [comment]
Still possible via blood jaunt is it not? But otherwise not quite the case anymore? That's the only thing I remember right now

**Comment by MarkSuckerberg** [comment]
More or less not the case now, blood jaunt or whatever means that allow you to cross the reserve borders are unrelated to this bug.
