### ISSUE TITLE
[BUG] ruin no go

### ISSUE THREAD

**Issue by HighPrincessErinys** [shiptest-ss13/Shiptest#431]
## Round ID:
no
## Testmerges:
irrelevant
## Reproduction:
map template place -> try ninja shrine, roommates, spooky crash, evil club
## hatred:
yeah so prefab like the IDIOT they are fucked up my ruins in https://github.com/shiptest-ss13/Shiptest/pull/413, presumably something to do with the suffix pathing, and did not fix it before it was fully merged. 

fix it! fix it!

**Comment by Cenrus** [comment]
The suffix is wrong, it needs to be the same as the dmm file name.
