### ISSUE TITLE
[BUG] Every turf on a ship gets deleted randomly, or better known as the "slimegirl trafficking" bug

### ISSUE THREAD

**Issue by rye-rice** [shiptest-ss13/Shiptest#445]
## Round ID:
NA
## Testmerges:
NA

## Reproduction:
This bug is very well known, but im putting it here for documentation sake

One of the oldest  and most bizzare bugs to grace this codebase. Randomly, every single turf will get delete on a ship, leaving the machinery and players behind.

The only known triggers are:
Selling a slimeperson on a cargo pad
whenever #364 triggers
Docking at a empty space (#454)

Images:
![image](https://user-images.githubusercontent.com/58402542/142320921-089f22c8-2fd3-4d67-9357-4a6e2af0225f.png)
![Screenshot_1388](https://user-images.githubusercontent.com/58402542/142321208-76de7a1f-d7a1-40f6-b306-113df0aa1f38.png)
![Screenshot_1518](https://user-images.githubusercontent.com/58402542/142753435-53f19eb1-0a13-4f04-ad34-3370148b33a7.png)

**Comment by rye-rice** [comment]
Added another example

**Comment by rye-rice** [comment]
it is over, what a way to end the year

**Comment by rye-rice** [comment]
It appears this is not fixed, @MarkSuckerberg, please reopen

**Comment by Zevotech** [comment]
the fucker is back with a vengeance i tell ya

**Comment by MarkSuckerberg** [comment]
> It appears this is not fixed, @MarkSuckerberg, please reopen

Unrelated issue.

**Comment by rye-rice** [comment]
the pharaoh smiles
