### ISSUE TITLE
[BUG] Explosive Decompression

### ISSUE THREAD

**Issue by AtlasRules** [shiptest-ss13/Shiptest#446]
## Round ID:

[391](https://shiptest.ga/stats/rounds/391), 392, and 393
## Testmerges:
#230: '[TEMP] Disable loadout costs' by AsciiSquid at commit a7399a3607
#218: 'Swifter's Ship Emporium!' by swifterjack at commit 02b52b5b6b
#405: 'Readds Rapid Shuttle Designator' by MarkSuckerberg at commit b85413fad0
#132: 'Readds Explosive Decompression' by MarkSuckerberg at commit 7e07d7cf40 (this one)
#313: 'Overmap Expansion #2' by retlaw34 at commit 6dd6e32326
#425: 'resprites the charcoal, navy, and burghundy suits, splits them into suit and jacket combos' by triplezeta at commit 9094943aa2
#438: 'Sound improvements' by CapnMachaddish at commit 2bdbc70ec4
#436: 'Revamps Cryo Consoles' by MarkSuckerberg at commit 48ba3adf41
#437: 'Adds Table Bells' by triplezeta at commit 8c4eff0256
#403: 'Adds Quirk specie-locks, vampire quirk.' by Ms-Mee at commit 58162740df

## Reproduction:
1. Have explosive decomp merged.
2. Wait for the crash.
3. While waiting, observe the infinite whirlwinds, things freezing that should not free (e.g, shutters, solars), and other strange phenomena.
4. Have the server crash and lose your shipcoins.

**Comment by terg-but-ius** [comment]
explosive decomp has had a history of being fucky, it seems the issues were not wholly fixed
can say that what atlas has pointed out is true

**Comment by MarkSuckerberg** [comment]
Thank you very very much for the feedback, but I'll be moving it to the PR itself.
