### ISSUE TITLE
[BUG] Osprey doesn't work at all

### ISSUE THREAD

**Issue by Imaginos16** [shiptest-ss13/Shiptest#452]
Issue reported from  Round ID: [424](https://shiptest.ga/stats/rounds/424) (Shiptest)

Reporting client version: 514.1557

Step 1: Get 850 cointests

Step 2: Buy an Osprey Class vessel.

Step 3: Get stuck on the title screen as the ship does not spawn at all

No idea what causes it

**Comment by MarkSuckerberg** [comment]
Should be fixed by 835f789
