### ISSUE TITLE
You can teleport outside of reality.

### ISSUE THREAD

**Issue by NanoCats** [shiptest-ss13/Shiptest#453]
Issue reported from Round ID: [426](https://shiptest.ga/stats/rounds/426) (Shiptest)

Reporting client version: 514.1557

Certain things, including but not limited to the hand teleporter, and the reactive teleporter armor, can teleport you beyond the realm of time and space, this is bad because there's nothing out there and no way back :)

Reproduction:

1. Stand near the edge of a planet(?) 
2. Use hand tele, 
3. find you're now outside,
4. SHITSHITSHITSHITSHIT (dead)

**Comment by PrefabQuasar** [comment]
known problem and also, it gets worse, you CAN get back from there, but only if you use smartmetal foam to make flooring, and build an APC and bluespace launchpad. at this point, you can freely teleport to ANY of the planets stored on the z-level.
Example:
![image](https://user-images.githubusercontent.com/78622038/142788368-9ca125cc-8ab8-4576-9c3a-ff69d757bc6b.png)

**Comment by rye-rice** [comment]
this is a part of overmap 2 #313. I god damn hoped nobody would abuse it since it was the only way to fix reebe

**Comment by rye-rice** [comment]
@MarkSuckerberg can i disable reebe now to fix this bug

**Comment by ZephyrTFA** [comment]
> @MarkSuckerberg can i disable reebe now to fix this bug

Yes

**Comment by MarkSuckerberg** [comment]
Fixed in respective PR, although we need to keep in mind that if NOTELEPORT is to be removed from encounters, we need to rework teleport code.
