### ISSUE TITLE
[BUG]Shuttle mass wonky

### ISSUE THREAD

**Issue by Superyodeler** [shiptest-ss13/Shiptest#46]
## Reproduction:
Shuttlecode calculate_mass() uses every shuttle tile in the game.
https://github.com/shiptest-ss13/Shiptest/blob/d55cae55c7edabdd721e97f66bb21e59f4d543e9/whitesands/code/modules/overmap/ships/simulated.dm#L182

Copy pasted from WS bug report because it looks like this is here too. Thanks to @MaltVinegar for reporting this.

**Comment by MarkSuckerberg** [comment]
*Possibly* resolved by #40

**Comment by MarkSuckerberg** [comment]
Appears fixed
