### ISSUE TITLE
[BUG] Genetics consoles fail to display information on discovered genes

### ISSUE THREAD

**Issue by Sun-Soaked** [shiptest-ss13/Shiptest#493]
## Round ID:
N/A, originally discovered during a testmerge and eventually replicated on a master branch localhost with no active testmerges

## Reproduction:
-Construct genetic engineering stuff
-Insert monke into machine
-Scramble to get human.
-See this:
![image](https://user-images.githubusercontent.com/45698967/144301894-ac9efd79-34b0-4800-9a48-2974d8a5a4c0.png)
-Go to solve mutation, successfully filling in all missing brackets. 
see this:
![image](https://user-images.githubusercontent.com/45698967/144302600-dc0685cb-099f-49d9-a811-26ebb299e802.png)
(note that brackets are no longer highlighted, confirming that the mutation is successfully "solved"
-Throw your genetic engineering degree out and cry.

**Comment by Jackriip** [comment]
Bump, seeing this on voidcrew as well

**Comment by dwasint** [comment]
Did you link it to the rnd server? 
![image](https://user-images.githubusercontent.com/82520990/151526108-1689109c-7d74-4467-970b-46de04cf133d.png)
i have not been able to replicate this issue if im linked to an rnd server

**Comment by SomeguyManperson** [comment]
Likely caused by a lack of a connected research server, i dont think genetics is planned to make a reappeaeance in its current state otherwise
