### ISSUE TITLE
[BUG] Alt-clicking containers broke, general weirdness with clicking cooldowns

### ISSUE THREAD

**Issue by mcmeiler** [shiptest-ss13/Shiptest#514]
## Reproduction: 
Try to alt click a container to open it, notice it doesn't work.

Pretty much *every* action has a click cooldown, be it picking up items, crowbarring floor tiles, etc.

**Comment by Sun-Soaked** [comment]
ahh, I did cause this didn't I

**Comment by Sun-Soaked** [comment]
alright, newest commit to the Research pr should fix these problems as of testing- they were caused by my 3am brain implementation of some altclick functionality and an unnessecary MELEE_COOLDOWN call.

**Comment by MarkSuckerberg** [comment]
Issue fixed in respective PR
