### ISSUE TITLE
[BUG] AI Full Camera Loss "Eyeobj not found"

### ISSUE THREAD

**Issue by Zevotech** [shiptest-ss13/Shiptest#535]
## Round ID:
First encounter: Round 482
encountered it in a later round where I was AI as well

## Reproduction:
When on a ship as an AI core, in the AI camera view (not in a borg), the screen may go completely black upon docking the ship. This error is indicated in chat by an incessant spamming of "ERROR: Eyeobj not found, creating new eyeobj"

1. Be an AI core on any ship (Bug specifically encountered on the Osprey and Metis)
2. Dock the ship in either empty space or on a planet (Bug was encountered twice in empty space, once on a planet(
3. Either immediately or sometime after docking, your camera view will be replaced with a black void, with the AI interface still there.

what if you
wanted to play ai
but byond said
eyeobj not found

**Comment by ZephyrTFA** [comment]
This is a known issue, you need to reconnect to fix it.

**Comment by Zevotech** [comment]
I know, and while I agree that reconnecting fixes it, it doesn't always seem to work. Second time I encountered it I reconnected about 3 times before it fixed, and the third I simply stayed in a borg until it just... left.

**Comment by PrefabQuasar** [comment]
it seems like this issue mainly/only occurs when leaving hyperspace, leading me to believe that the hyperspace tiles are qdel'ing the AI eyeobj whenever the eye gets left behind during transit, possibly caused by the eye moving during the process

**Comment by triplezeta** [comment]
if thats the case then this issue can be fixed by making hyperspace not qdel things (no longer necessary thanks to virtual zs)

**Comment by benbot16** [comment]
issue seems to be something different, think I found a fix for it though. Just gotta test it a few times.

**Comment by Zevotech** [comment]
This is still happening, and happened several times in round 775
