### ISSUE TITLE
[BUG] Rapid Shiptest Disintigration Syndrome

### ISSUE THREAD

**Issue by PrefabQuasar** [shiptest-ss13/Shiptest#536]
## Round ID:
[514](https://shiptest.ga/stats/rounds/514)

## Testmerges:
#403 
#230 
#432 
#522 
#521 
These testmerges are only for the most recent occurence, this bug has occured with wholly different sets of testmerges.

## Reproduction:
Occasionally while a shiptest is flying, even on tiles with no hazard objects, massive amounts of explosions occur, fully destroying the ship, presumably these are the same explosions as used for hitting space hazards at 0% integrity. Cause for this bug is currently unknown, and it has occured in the past with wholly different testmerges.

**Comment by MarkSuckerberg** [comment]
has this happened at all recently? this doesn't sound like a SGT
