### ISSUE TITLE
[BUG] Holopads are broken as fuck

### ISSUE THREAD

**Issue by Zevotech** [shiptest-ss13/Shiptest#537]
Issue reported from  Round ID: [515](https://shiptest.ga/stats/rounds/515) (Shiptest)

Reporting client version: 514.1571

Most if not all holopads seem to be broken right now with the current TM's this has to be fixed quickly.

**Comment by Azarak** [comment]
working on fixing that

**Comment by Azarak** [comment]
Should be fixed when server is updated
