### ISSUE TITLE
[BUG] Paramedic jacket has no sprite

### ISSUE THREAD

**Issue by rye-rice** [shiptest-ss13/Shiptest#54]
## Testmerges:

None.

## Reproduction:

![image](https://user-images.githubusercontent.com/58402542/123500735-f9865900-d5f4-11eb-8e22-96992e32f7a8.png)

right click your suit as paramedic

**Comment by rye-rice** [comment]
this is caused, according to swifter, because paramedics jacket is a subtype of labcoat, and the labcoat icons were modularised. Oops

**Comment by swifterjack** [comment]
> 
> 
> this is caused, according to swifter, because paramedics jacket is a subtype of labcoat, and the labcoat icons were modularised. Oops

i'm not actually sure thats the cause, thats just my theory

**Comment by PetMudstone** [comment]
I just checked and yep, the labcoats were modularized so that they lead to sprites under "whitesands..." but there aren't any sprites for the paramedic's jacket in the relevant .dmi files. Hence, missing sprites.

**Comment by PetMudstone** [comment]
Fixed as of #120.
