### ISSUE TITLE
[BUG] Crystal Goliaths Never Stop Firing Projectiles

### ISSUE THREAD

**Issue by Zevotech** [shiptest-ss13/Shiptest#562]
## Round ID:
[539](https://shiptest.ga/stats/rounds/539), currently ongoing.

## Testmerges:
#230: '[TEMP] Disable loadout costs' by AsciiSquid at commit a7399a3607
#459: 'Interrim Research Rework: Of Departments and Trading' by MemedHams at commit 7b6822c3b2
#522: 'Map zones and virtual levels' by Azarak at commit 6d75ceffe2
#505: 'Vinethud vote notification' by Zevotech at commit 7daed97ea6
#521: 'Xenomorph Tweaks' by MemedHams at commit af9c6a2c25
#498: 'Gorlex Hyena-Class Salvage Ship' by Apogee-dev at commit bd0ae6f603
#530: 'Kapu's BetterLimbs port' by E-MonaRhg at commit 3b086554f2

## Reproduction: It seems to be just caused by the crystal goliath existing, but its presence on a sandplanet or closeness to a ship might be causing it as well.
![image](https://user-images.githubusercontent.com/95449138/147632402-1b28d6e1-7ee4-468a-acaf-84330568796e.png)

**Comment by Zevotech** [comment]
non-optional bullethell lavaland elite my behated! :withered:

**Comment by MarkSuckerberg** [comment]
Error caused by #459, probably resolved? But either way, this is feedback for that.
