### ISSUE TITLE
[BUG] Amputation head duplicate and warping.

### ISSUE THREAD

**Issue by zestybastard** [shiptest-ss13/Shiptest#571]
**Round ID: [548](https://shiptest.ga/stats/rounds/548)**

## Testmerges:

Probably Kapulimbs.

## Reproduction:

Take a person, amputate their head. Amputate the head of another body. Place the head of the first amputee on the second, it will "reject" and send their head to the debug zone, replacing it with a bald caucasian head. Repeating the procedure with the "new" head on the same body will warp the new head to the body's position once the amputation surgery completes.

**Comment by zestybastard** [comment]
Update: Most limbs can fail to replace and duplicate now, for some reason.

**Comment by MarkSuckerberg** [comment]
I have a sneaking suspicion that it's my bodgecode for limiting what bodypart types can be attached. Will go over that again
