### ISSUE TITLE
[BUG] prostetic replacement surgery on ipcs drops the head as an item

### ISSUE THREAD

**Issue by nogoodidea** [shiptest-ss13/Shiptest#573]
## Reproduction:
1 use surgery to behead an ipc
2 put prostetic replace ment to put the ipc head on an other ipc
3 see that there are now 2 heads (the one one the ipc and one droped on the floor)
4 damage to the ipc's head shows on the head item
5 dusting the ipc head causes all orgens in the head to be distroyed

might work on every speices but i only was able to test with ipcs

**Comment by MarkSuckerberg** [comment]
Fixed before merge of #530
