### ISSUE TITLE
[BUG] access on the twinkle shine is fucked

### ISSUE THREAD

**Issue by rye-rice** [shiptest-ss13/Shiptest#586]
## Reproduction: Spawn in as captain of the twinkle shine 
Fail to enter your own office

**Comment by Zevotech** [comment]
> RETRIEVE ARMS FROM CHEST

> YOU CANNOT ACCESS YOUR OWN OFFICE

**Comment by fighterslam** [comment]
according to the map file the door has legitimately no access requirements, What

**Comment by rye-rice** [comment]
what

**Comment by rye-rice** [comment]
how

**Comment by UltraNumeron** [comment]
yeah its very scuffed right now to do get into your officer or the armory you need to do fucky shit like break windows to get an emag.
