### ISSUE TITLE
[BUG] Ashwalker shrine ruin doesnt spawn

### ISSUE THREAD

**Issue by rye-rice** [shiptest-ss13/Shiptest#602]
## Reproduction:

Spawn "ashwalker shrine" in map template -- place
Or find one by chance
It doesn't load.

**Comment by MarkSuckerberg** [comment]
Map file is `lavaland_surface_ashwalker_shrine.dmm` while code says it's just `ashwalker_shrine.dmm`. Easy fix for whoever wants to do it
