### ISSUE TITLE
Ships that aren't spawned through buying or the shuttle manip are bugged. [BUG]

### ISSUE THREAD

**Issue by swifterjack** [shiptest-ss13/Shiptest#609]
## Testmerges:
The following pull requests are currently test merged:
#230: '[TEMP] Disable loadout costs' by AsciiSquid at commit a7399a3607
#459: 'Interrim Research Rework: Of Departments and Trading' by MemedHams at commit f93bd19309
#522: 'Map zones and virtual levels' by Azarak at commit fdc1cd65ad
#505: 'Vinethud vote notification' by Zevotech at commit 7daed97ea6
#521: 'Xenomorph Tweaks' by MemedHams at commit 9edf4bb03e
#530: 'Kapu's BetterLimbs port' by E-MonaRhg at commit 76b3efc6eb
#572: 'The Dronetestening' by Pockets-byte at commit c32123fe2c
#558: 'speech controllers and hearers_in_view improvements' by jupyterkat at commit f5f728545e

## Reproduction:
Find ship in ruin, try to open helm console, it doesn't open, day ruined. Alternatively, spawn ship in using debug mode - > place template, try to open helm console, it doesn't open, day ruined.

**Comment by MarkSuckerberg** [comment]
> ## Round ID:[576](https://shiptest.ga/stats/rounds/576)
> ## Testmerges:
> 
> The following pull requests are currently test merged: #230: '[TEMP] Disable loadout costs' by AsciiSquid at commit [a7399a3](https://github.com/shiptest-ss13/Shiptest/commit/a7399a36074673eed97258bef84424ad208dbf20) #522: 'Map zones and virtual levels' by Azarak at commit [fdc1cd6](https://github.com/shiptest-ss13/Shiptest/commit/fdc1cd65ad0f469914e75a9c29f29ee7e2dc4982) #505: 'Vinethud vote notification' by Zevotech at commit [7daed97](https://github.com/shiptest-ss13/Shiptest/commit/7daed97ea6dfd981b0be094efa3dad1d6945bba4) #521: 'Xenomorph Tweaks' by MemedHams at commit [3993567](https://github.com/shiptest-ss13/Shiptest/commit/39935670fc366e31746a374a67ec503a70a35909) #530: 'Kapu's BetterLimbs port' by E-MonaRhg at commit [ab1b0f6](https://github.com/shiptest-ss13/Shiptest/commit/ab1b0f6c8fff7a828e8b833360d97e5549239177) #572: 'The Dronetestening' by Pockets-byte at commit [82f0f99](https://github.com/shiptest-ss13/Shiptest/commit/82f0f99e423de0e62452d3ceb0c98de454399ce3) #589: 'Spitfire 2: Geneva Conventions Be Damned' by swifterjack at commit [21263c6](https://github.com/shiptest-ss13/Shiptest/commit/21263c6bff435d4d97df3b0fbf9f65f9b2fbc612) #614: 'Two minor SGT fixes, hopefully' by MarkSuckerberg at commit [c8729db](https://github.com/shiptest-ss13/Shiptest/commit/c8729dbdcce1ef918ad9c89696df000f6bac3da2) #604: 'Scrapper-A Tweaks' by Omppusolttu at commit [4bf5da3](https://github.com/shiptest-ss13/Shiptest/commit/4bf5da3df877e51e16ace21a1bddfc67f44a5b53)
> ## Reproduction:
> 
> Unsure. Happened on a Kugelblitz SSV Does Not Exist in round 576. No known way to fix this bug in round so far. Helm console and autopilot consoles can not be used, making ship impossible to pilot. Making a new helm console does not seem to fix this.

**Comment by MarkSuckerberg** [comment]
Fixed with #613
