### ISSUE TITLE
Oil thrusters refuse to show any amount of fuel in them above 5%[BUG]

### ISSUE THREAD

**Issue by swifterjack** [shiptest-ss13/Shiptest#611]
## Testmerges:
The following pull requests are currently test merged:
#230: '[TEMP] Disable loadout costs' by AsciiSquid at commit a7399a3607
#459: 'Interrim Research Rework: Of Departments and Trading' by MemedHams at commit 5eb6e25a45
#522: 'Map zones and virtual levels' by Azarak at commit fdc1cd65ad
#505: 'Vinethud vote notification' by Zevotech at commit 7daed97ea6
#521: 'Xenomorph Tweaks' by MemedHams at commit 39935670fc
#530: 'Kapu's BetterLimbs port' by E-MonaRhg at commit eb416f1b2f
#572: 'The Dronetestening' by Pockets-byte at commit 82f0f99e42
#589: 'Spitfire 2: Geneva Conventions Be Damned' by swifterjack at commit 99b1bc9870

## Reproduction:
Fill oil thruster with oil - > Check helm console - > See it only has 5% fuel.

**Comment by zestybastard** [comment]
This isn't a Genenva issue, just want to say for clarity. Old Spitfire still had this problem as well.
