### ISSUE TITLE
Kapulimbs seem to not show sprites for some species[BUG]

### ISSUE THREAD

**Issue by swifterjack** [shiptest-ss13/Shiptest#612]
## Testmerges:
The following pull requests are currently test merged:
#230: '[TEMP] Disable loadout costs' by AsciiSquid at commit a7399a3607
#459: 'Interrim Research Rework: Of Departments and Trading' by MemedHams at commit 5eb6e25a45
#522: 'Map zones and virtual levels' by Azarak at commit fdc1cd65ad
#505: 'Vinethud vote notification' by Zevotech at commit 7daed97ea6
#521: 'Xenomorph Tweaks' by MemedHams at commit 39935670fc
#530: 'Kapu's BetterLimbs port' by E-MonaRhg at commit eb416f1b2f
#572: 'The Dronetestening' by Pockets-byte at commit 82f0f99e42
#589: 'Spitfire 2: Geneva Conventions Be Damned' by swifterjack at commit 99b1bc9870

## Reproduction:
~~Get delimbed as, in my experience so far, a lizard, a kepori, a podperson, an ipc, a snail, a digitgrade lizard, or human. No limb sprite. Can't see it!~~

Maintainer edit:

Spawning a limb directly using `spawn` or a limbgrower will produce a limb with an invalid `icon` if it is `greyscale only`.

**Comment by Kapu1178** [comment]
Known issue, still thinking of a decent way to fix.

**Comment by Sun-Soaked** [comment]
This might be pedantic but should we be closing issues that are unresolved 
note that we still have the vague "slimegirl traffiking" issue up somewhere down the list

**Comment by tiramisuapimancer** [comment]
I don't technically have a say in this but you should definitely probably leave issues unclosed until they're resolved
