### ISSUE TITLE
Spacepods are over-oxygenized[BUG]

### ISSUE THREAD

**Issue by swifterjack** [shiptest-ss13/Shiptest#620]
## Testmerges:
The following pull requests are currently test merged:
#230: '[TEMP] Disable loadout costs' by AsciiSquid at commit a7399a3607
#522: 'Map zones and virtual levels' by Azarak at commit fdc1cd65ad
#505: 'Vinethud vote notification' by Zevotech at commit 7daed97ea6
#521: 'Xenomorph Tweaks' by MemedHams at commit 39935670fc
#530: 'Kapu's BetterLimbs port' by E-MonaRhg at commit ab1b0f6c8f
#572: 'The Dronetestening' by Pockets-byte at commit 82f0f99e42
#589: 'Spitfire 2: Geneva Conventions Be Damned' by swifterjack at commit 21263c6bff
#614: 'Two minor SGT fixes, hopefully' by MarkSuckerberg at commit c8729dbdcc
#604: 'Scrapper-A Tweaks' by Omppusolttu at commit 4bf5da3df8

## Reproduction:
Make a spacepod, put a default air tank in it. Die of over-oxygenization.

**Comment by MrSamu99** [comment]
This is no more actual since pods are nuked out

**Comment by Sun-Soaked** [comment]
someone with codebase perms might as well go through the issue list and carpet bomb anything with spacepods connected to it
