### ISSUE TITLE
[BUG]Ruins spawning with space tiles.

### ISSUE THREAD

**Issue by PrefabQuasar** [shiptest-ss13/Shiptest#626]
## Round ID:

Round: 578

## Testmerges:
#230 
#522 
#505 
#521 
#530 
#572 
#589 
#614 
#604 
#605 

## Reproduction:
Go to a planet which has had a ruin affected by this loaded, Ex. Fortress of Solitide, this occurs on multiple other ruins however. Find that certain tiles of the ruin are either space tiles or vacuum atmos tiles. These turfs seem to occur where turf passthroughs should be.

**Comment by Sun-Soaked** [comment]
the fortress of solitude bug is explicitly a mapper fuckup caused by me- but the vacuum tiles seem to be something else entirely, since the affected ruins don't actually seem to have airless tiles as I originally assumed.

**Comment by Zevotech** [comment]
bumping this, its a huge issue and still happens way too often on sand and jungle planets in particular.

**Comment by Zevotech** [comment]
This issue is (presumably) caused by planetgen order. It spawns the ruin before most of the planet generates, leading to any non-closed off areas having their atmos sucked out by space before the rest of the planet loads.
