### ISSUE TITLE
[BUG] sentient elites not dropping correct drops

### ISSUE THREAD

**Issue by UltraNumeron** [shiptest-ss13/Shiptest#637]
## Round ID:
[590](https://shiptest.ga/stats/rounds/590)

## Testmerges:
#230
#522
#505
#521
#530
#572
#589
#614
#604
#605
#607
#560

## Reproduction:
Apply stabilized regenerative core to tumor, make sentientient elite and kill it and the chest has just one tendril item and nothin else.

**Comment by FalloutFalcon** [comment]
That's not an intended mechanic from looking at the code! Either way I don't want this as a feature.
