### ISSUE TITLE
[BUG] Infinite cloth

### ISSUE THREAD

**Issue by Onule** [shiptest-ss13/Shiptest#643]
## Reproduction:

Cut up a jumpsuit, receive 5 cloth.
Make a white jumpsuit with 4 cloth.
Gain 1 cloth in the process.

**Comment by Nobelium-XVIII** [comment]
This will be bad for the economy i think

**Comment by zestybastard** [comment]
I have also seen this done with scarves, and there is the menu abuse bug too

**Comment by Obliii** [comment]
How do you even cut up scarves and jumpsuits?

**Comment by redguy999** [comment]
> How do you even cut up scarves and jumpsuits?

Use a knife or something sharp on it, you’ll get a prompt for if you wanna cut it or not.
