### ISSUE TITLE
[BUG] Tumor generated with space tiles

### ISSUE THREAD

**Issue by PrefabQuasar** [shiptest-ss13/Shiptest#659]
## Round ID:
Round 604

## Testmerges:
#230: '[TEMP] Disable loadout costs' by AsciiSquid at commit a7399a3607
#505: 'Vinethud vote notification' by Zevotech at commit 7daed97ea6
#521: 'Xenomorph Tweaks' by MemedHams at commit e49072f296
#530: 'Kapu's BetterLimbs port' by E-MonaRhg at commit ab1b0f6c8f
#589: 'Spitfire 2: Geneva Conventions Be Damned' by swifterjack at commit 26b481da0e
#614: 'Two minor SGT fixes, hopefully' by MarkSuckerberg at commit c8729dbdcc
#607: 'SV Bluntsmoken - God's gift to spess' by DrDuckedGoose at commit cf2ba2f540
#558: 'speech controllers and hearers_in_view improvements' by jupyterkat at commit e72341682e
#459: 'Interrim Research Rework: Of Departments and Trading' by MemedHams at commit acb0e3cf34

## Reproduction:
![ruh_roh](https://user-images.githubusercontent.com/78622038/149447215-9675ef35-a9da-44c3-a12d-6eb9e7d227d8.png)
Above image is currently all the information I have on this issue, if tumors were recently changed to generating as ruins instead of landmarks, it's possible this is related to Issue #626

**Comment by Sun-Soaked** [comment]
My original suspicion was that there was a "literally just a tumour" ruin, but I know that can't be true in this case- the planet in question also had a seed vault on it, which would've been it's ruin slot.

**Comment by SomeguyManperson** [comment]
Think this was fixed?
