### ISSUE TITLE
[BUG] Cannot hear some people speaking.

### ISSUE THREAD

**Issue by Zevotech** [shiptest-ss13/Shiptest#661]
## Round ID:
[606](https://shiptest.ga/stats/rounds/606) and 607

## Testmerges:
#230: '[TEMP] Disable loadout costs' by AsciiSquid at commit a7399a3607
#505: 'Vinethud vote notification' by Zevotech at commit 7daed97ea6
#521: 'Xenomorph Tweaks' by MemedHams at commit e49072f296
#530: 'Kapu's BetterLimbs port' by E-MonaRhg at commit ab1b0f6c8f
#589: 'Spitfire 2: Geneva Conventions Be Damned' by swifterjack at commit 26b481da0e
#614: 'Two minor SGT fixes, hopefully' by MarkSuckerberg at commit c8729dbdcc
#607: 'SV Bluntsmoken - God's gift to spess' by DrDuckedGoose at commit cf2ba2f540
#558: 'speech controllers and hearers_in_view improvements' by jupyterkat at commit e72341682e
#459: 'Interrim Research Rework: Of Departments and Trading' by MemedHams at commit acb0e3cf34

## Reproduction:
Occasionally during a round, when someone speaks nothing will appear in chat or above their head. LOOC and emotes still work.
This may be caused by #558

**Comment by MarkSuckerberg** [comment]
Due to #558, haven't heard of this issue continuing
