### ISSUE TITLE
[BUG] IPC Repair Machinery Doesn't Work

### ISSUE THREAD

**Issue by Skies-Of-Blue** [shiptest-ss13/Shiptest#667]
## Round ID: 
[609](https://shiptest.ga/stats/rounds/609)

## Testmerges: 
#305: '[PLACEHOLDER UNTIL HEDIFF] [DNM] Wounds' by retlaw34 at commit 0d2b637af9
#230: '[TEMP] Disable loadout costs' by AsciiSquid at commit a7399a3607
#505: 'Vinethud vote notification' by Zevotech at commit bd1c2b9bb3
#652: 'Weathers' by Azarak at commit 12ade89119
#607: 'SV Bluntsmoken - God's gift to spess' by DrDuckedGoose at commit cf2ba2f540

## Reproduction:
Find a damaged IPC, or get damaged yourself. Attempt to conduct repair machinery with the standard tools. Notice that it attempts to repair, but upon completion, no damage is healed. Notice that the repair does not attempt to repeat. Notice that you are weeping gently, for your IPC Power Creep is no more.

**Comment by Zevotech** [comment]
:WAA:

**Comment by Ms-Mee** [comment]
Which tools did you use to try and repair which damage?

**Comment by Skies-Of-Blue** [comment]
Standard engineering tools. Namely, a screwdriver to start the surgery, a welder to repair brute, and wirecutters for burn. Worth noting that standard IPC repair can be conducted with a welder and wires, the primary issue is with the Repair Machinery surgery.

**Comment by Kurgis** [comment]
Also struggled with this same issue, I accidentally screwed open an IPC using a lit welder, and that did something which made ending or continuing the surgery impossible.

**Comment by Garen7** [comment]
unable to reproduce on local so either im missing something or this is related to a test merge, maybe related to #305 ?

**Comment by Ms-Mee** [comment]
> unable to reproduce on local so either im missing something or this is related to a test merge, maybe related to #305 ?

It has to be if it actually happens.

**Comment by rye-rice** [comment]
It is related to wounds, repair machinery is a copy paste job that @AsciiSquid did that so happened to break
