### ISSUE TITLE
GPS devices appear to be broken [BUG]

### ISSUE THREAD

**Issue by AquillaF** [shiptest-ss13/Shiptest#734]
## Round ID:
[638](https://shiptest.ga/stats/rounds/638)

## Testmerges:

#652: 'Weathers' by Azarak at commit 12ade89119
#607: 'SV Bluntsmoken - God's gift to spess' by DrDuckedGoose at commit 6d1342f9c1
#690: 'AI EyeObjects are now smarter about being deleted' by ZephyrTFA at commit 4e78910782
#729: 'Removes Metacoins/Antag Tokens, Minor Loadout Rework' by MarkSuckerberg at commit 0778406a74
#723: 'Configurable Overmap Size' by MarkSuckerberg at commit 004d8af8c3
#711: 'The Great Handgun Re-Flattening' by Apogee-dev at commit cdc6aabb0f
## Reproduction:
GPS devices appear to be broken, no names or anything showing up, made and new one to see if it was just the one and it was still busted
![image](https://user-images.githubusercontent.com/88289697/151629719-de766aae-12f8-4efd-bdc5-47858fa20b39.png)

**Comment by AquillaF** [comment]
never mind, something must have just been a bit fucky but its fine now

**Comment by Kurgis** [comment]
Experienced same issue before it passed in the same manner, unsure of how to replicate however.
