### ISSUE TITLE
[FEATURE] Functioning Ship Building

### ISSUE THREAD

**Issue by PrefabQuasar** [shiptest-ss13/Shiptest#738]
## Name of feature:

The ability to actually create ships from scratch with a functioning overmap object. Please god.
### Additional Info:

Currently it is as far as I know, either impossible or next to impossible to create a functioning ship in-round, as all current methods of creating a new ship fail to create an overmap object, and even if an admin creates and links an overmap object to the ship, the helm console will bluescreen when used.

**Comment by Sylphily** [comment]
The shuttle crap worked first try for me last uptime so it might of some how gotten fixed?
