### ISSUE TITLE
[BUG] AI constantly gets kicked out of borg shells

### ISSUE THREAD

**Issue by Zevotech** [shiptest-ss13/Shiptest#743]
## Round ID: 
642

## Testmerges:
#607: 'SV Bluntsmoken - God's gift to spess' by DrDuckedGoose at commit 6d1342f9c1
#690: 'AI EyeObjects are now smarter about being deleted' by ZephyrTFA at commit 4e78910782
#729: 'Removes Metacoins/Antag Tokens, Minor Loadout Rework' by MarkSuckerberg at commit 0778406a74
#723: 'Configurable Overmap Size' by MarkSuckerberg at commit 004d8af8c3
#711: 'The Great Handgun Re-Flattening' by Apogee-dev at commit cdc6aabb0f

## Reproduction:
Playing AI seems to be fucked at the moment, I got put in an AI as an MMI and CONSTANTLY kept getting kicked out of controlling my shells and got sent to my AI core cam for no reason in particular. Sometimes it stopped happening for a few minutes but seemed to pop back up again a lot and would either kick me out of the borg after 1-2 seconds or it kicked me out instantly.

**Comment by MarkSuckerberg** [comment]
Extremely likely caused by #690, which isn't TM'd anymore.

**Comment by Zevotech** [comment]
Bad news, this happened last round to an AI. Its back.

**Comment by ZephyrTFA** [comment]
This is because it was merged. It was determined that this occurring is better than your eye just being deleted entirely

**Comment by Zevotech** [comment]
:constipation:
