### ISSUE TITLE
[BUG] Krokodil zombies lack head sprites

### ISSUE THREAD

**Issue by PrefabQuasar** [shiptest-ss13/Shiptest#755]
## Round ID:
[648](https://shiptest.ga/stats/rounds/648)

## Testmerges:
[#607: 'SV Bluntsmoken - God's gift to spess' by DrDuckedGoose at commit 6d1342f9c1](https://github.com/Shiptest-SS13/Shiptest/pull/607)
[#690: 'AI EyeObjects are now smarter about being deleted' by ZephyrTFA at commit 4e78910782](https://github.com/Shiptest-SS13/Shiptest/pull/690)
[#729: 'Removes Metacoins/Antag Tokens, Minor Loadout Rework' by MarkSuckerberg at commit 0778406a74](https://github.com/Shiptest-SS13/Shiptest/pull/729)
[#723: 'Configurable Overmap Size' by MarkSuckerberg at commit 004d8af8c3](https://github.com/Shiptest-SS13/Shiptest/pull/723)
[#711: 'The Great Handgun Re-Flattening' by Apogee-dev at commit cdc6aabb0f](https://github.com/Shiptest-SS13/Shiptest/pull/711)
[#724: 'What if I Maintained the Tide-class, Hightide-class, Trunktide-class, Metis-class, Bogatyr-class, Lamia-class, and Wright-class Shiptests Ahahaha (Now with an even longer PR title because GitHub doesn't actually limit them for some reason wow isn't that amazing?)' by PrefabQuasar at commit e6ac13ad2f](https://github.com/Shiptest-SS13/Shiptest/pull/724)
[#674: 'Inteq risk management group, a neutral PMC faction' by Ebin-Halcyon at commit 695b3a2bc7](https://github.com/Shiptest-SS13/Shiptest/pull/674)
[#749: 'Resprites some Kepori color matrix gear to not look obnoxiously large.' by Ebin-Halcyon at commit 934f5d3666](https://github.com/Shiptest-SS13/Shiptest/pull/749)

## Reproduction:
Become addicted to krokodil. Become a krokodil zombie. Behold.
![image](https://user-images.githubusercontent.com/78622038/152237529-d584febe-496a-4385-bac0-0e10883e23e5.png)

**Comment by Kapu1178** [comment]
haha i knew this would bite me in the ass

I know the likely cause.
