### ISSUE TITLE
[BUG] Deep Core Miner linking

### ISSUE THREAD

**Issue by Syrox25** [shiptest-ss13/Shiptest#758]
## Round ID:
[649](https://shiptest.ga/stats/rounds/649)

## Testmerges:
Unknown

## Reproduction:

Linking process is incredibly scuffed:

"Deepcore Mining Control Hub" can be linked to both other hubs AND itself, doing so clogs the entire system.
If 3 hubs are linked together and a "Deep Core Bluespace Drill" is linked to one of said hubs, it connects to all 3 hubs, meaning that all 3 can only support equal to or less than a single hub on its own

Linking 4 hubs to the same "Bluespace Material Hopper" also causes issues as  the same linking nightmare happens and once the Hopper is full of links, you cannot connect unless destroyed  and rebuilt

This becomes an issue when the hubs are accidently linked as there is no way to unlink machines without destroying them (15 laser shots)

Suggestion- Do not allow Hubs to connect to each other and limit Hopper-Hub connections to 1, if a new hopper is linked, the old one disconnects or is refused

1 hub should have:
1 hopper
9 Drills

**Comment by MarkSuckerberg** [comment]
lmao, I guess you could say this was fixed
