### ISSUE TITLE
[BUG] Baseturf replacement doesn't work.

### ISSUE THREAD

**Issue by Latentish** [shiptest-ss13/Shiptest#793]
## Round ID:
Not from a round, from mapping and trying to make baseturf replacement work.

## Reproduction:
All turfs have a baseturf variable, whether they be walls or floors. The way these should work, is changing this variable should change what new turf will be spawned when you break the parent turf. This process unreliably either does nothing at all, or adds the baseturf you varedit in to the list of baseturfs. This results in the new variable edit being ignored either way, causing the original baseturf to override the new edit.
EG.
![image](https://user-images.githubusercontent.com/55075747/153118131-b932527d-1996-4f25-95de-360c902df8ab.png)
![image](https://user-images.githubusercontent.com/55075747/153118143-5dbb230d-d343-42ab-94a8-69b6f38e2043.png)
![image](https://user-images.githubusercontent.com/55075747/153118302-f37ac01b-337a-4f91-a09b-dc62b5d7cc63.png)
Continuing on with how baseturfs don't work how they should, the baseturf helper/editor also does not work how it should. After loading it with the baseturf variable, it just, added the turf I asked for into the list, which got overridden like before. The same thing happens when loading a single turf into the "turf to replace" variable. But what makes these especially busted, is that adding a list of turfs to the "turf to replace variable" does override the baseturf finally, but gives you an unpredictable baseturf. Like space, or lava, rather than the one you told it to replace it with.
![image](https://user-images.githubusercontent.com/55075747/153120086-dd52ef6b-d132-4aec-85c7-dd181bbd9229.png)
![image](https://user-images.githubusercontent.com/55075747/153120095-0d9650c5-cdae-44c5-95a5-c627012f9c4e.png)
![image](https://user-images.githubusercontent.com/55075747/153120104-83153886-2338-4e76-9b9b-564cf0a95626.png)

**Comment by MarinaGryphon** [comment]
Potentially related to #648.

**Comment by Latentish** [comment]
This was a misunderstanding of baseturfs as a whole. The way to fix this: Don't varedit turfs at all.
