### ISSUE TITLE
[BUG] Geneva Defibs Being Painful To Power

### ISSUE THREAD

**Issue by terg-but-ius** [shiptest-ss13/Shiptest#809]
## Reproduction: 
Step 1: Play on a Geneva
Step 2: See that the defibs are unpowered at the start as they lack cells
Step 3: Realize there is no cell charger.
Step 4: Realize that you need to put cells in the APCs just to have functional defibs aside from le epic combat defibs.
Step 5: p a i n

**Comment by Sylphily** [comment]
I believe this is on purpose, and you can easily get batteries via botany so it's kinda a weird gimmick

**Comment by Dimasw99** [comment]
Leaving a potato battery with some seeds and wires would give that hint

**Comment by swifterjack** [comment]
> I believe this is on purpose, and you can easily get batteries via botany so it's kinda a weird gimmick

a lot smarter than me just forgetting to make them the charged subtype
