### ISSUE TITLE
skipper-class has no plasma in the plasma tank

### ISSUE THREAD

**Issue by TheNeoGamer42** [shiptest-ss13/Shiptest#82]
Issue reported from  Round ID: 55 (Girlboss Station: Shiptest)

Reporting client version: 513.1536

exactly what the title says, its a scam, a fraud, theres no plasma in the damn plasma atmos tank

**Comment by triplezeta** [comment]
Additional skipper issues:

There are several doublepipes on the map in the atmospherics/engineering section of the ship

No holopad 😢 

no canister attachment ports to do atmos with,,

**Comment by TheNeoGamer42** [comment]
well theres actually a holopad in the room BELOW the bridge, with the wood flooring

**Comment by triplezeta** [comment]
i placed that there with admin fuckery

**Comment by TheNeoGamer42** [comment]
huh, its always there usually from when I've played it so I guess you've spawned it every time?

**Comment by triplezeta** [comment]
yes
