### ISSUE TITLE
[BUG] Missing Cryogenic Oversight Console On Some Ships

### ISSUE THREAD

**Issue by VeteranKyl** [shiptest-ss13/Shiptest#845]
## Round ID: 
N/A

## Testmerges:
800, 819, 790 ,770, 768 ,764, 757, 726, 839, 838

## Reproduction: 
Ships such as the **Solar-Class Research Vessel** and the **Bubble-Class Colonial Ship** lack cryogenic oversight consoles. This means the captains of these ships are unable to control whether crew can spawn or not, what roles are available, nor set a joining memo. This can cause issues, as people may join assuming an open goal ship, when instead the captain may have a specific mission or theme in mind. In addition, this means that a captain can't control who or if anyone can join.

**Comment by UltraNumeron** [comment]
skipper has the same issue
