### ISSUE TITLE
[BUG] Paper Detroit Is BACK?

### ISSUE THREAD

**Issue by Zevotech** [shiptest-ss13/Shiptest#860]
## Round ID:
[690](https://shiptest.ga/stats/rounds/690)

## Testmerges:
[#816: 'Overmap Rework [DNM]' by MarkSuckerberg at commit ebc3e5790d](https://github.com/Shiptest-SS13/Shiptest/pull/816)
[#726: 'KapuLimbs v1.1: Update Icons Soft Refactor & Clockvox' by Kapu1178 at commit 3c71b7a6f8](https://github.com/Shiptest-SS13/Shiptest/pull/726)
[#824: 'fixes breathing, updates lung code' by jupyterkat at commit 19b5aeb8ec](https://github.com/Shiptest-SS13/Shiptest/pull/824)
[#778: 'Temporarily removes Hyena from purchase' by Apogee-dev at commit 21c6874360](https://github.com/Shiptest-SS13/Shiptest/pull/778)
[#859: '[DNM] Revert "Fix more hanging references"' by Kapu1178 at commit d00da05847](https://github.com/Shiptest-SS13/Shiptest/pull/859)
[#800: 'Chisels now work on all atoms that can be smoothed' by ZephyrTFA at commit b7440a813f](https://github.com/Shiptest-SS13/Shiptest/pull/800)
[#839: 'BYO-class' by triplezeta at commit 6e06554104](https://github.com/Shiptest-SS13/Shiptest/pull/839)
[#826: 'Pill trilogy: The sweet return of the successor unchained' by Dimasw99 at commit 991a6c60d7](https://github.com/Shiptest-SS13/Shiptest/pull/826)

## Reproduction:
The ruin has spawned again despite being removed from the rotation in an event to destroy Paper Detroit

![image](https://user-images.githubusercontent.com/95449138/154821851-39f713cb-ede0-41d7-b122-a547f5172912.png)

Two people died to this INJUSTICE of a ruin.

**Comment by Zevotech** [comment]
God I Fucking Hate Paper Detroit

**Comment by triplezeta** [comment]
how

**Comment by HighPrincessErinys** [comment]
this isnt Paper Detroit... its Paper Kalamazoo...








woe...................
