### ISSUE TITLE
[BUG] Expulsion Thrusters Don't Require Fuel

### ISSUE THREAD

**Issue by untrius** [shiptest-ss13/Shiptest#867]
## Reproduction:
1) Build or map an expulsion thruster
2) Build or map a fueled engine preheater adjacent to it
3) Make sure they are aligned correctly.   If you build them, the thruster may have to be facing the opposite direction.  Check that a fuel gauge is displayed on the helm to confirm.
4) Do not fuel the preheater
5) Turn off all other thrusters on the ship
6) Turn on the unfueled expulsion thruster
7) Fly around the overmap while using no fuel

**Comment by MarkSuckerberg** [comment]
https://github.com/shiptest-ss13/Shiptest/blob/0dbe5a6c8e08bfd6c9367aa6cc34d40cc6439eb0/whitesands/code/game/machinery/shuttle/shuttle_heater.dm#L131
^This should be `total_moles()` not `return_volume()`.

**Comment by MarkSuckerberg** [comment]
Closed by #926
