### ISSUE TITLE
[BUG] Slapping makes you clack your beak

### ISSUE THREAD

**Issue by rye-rice** [shiptest-ss13/Shiptest#880]
## Round ID:

[699](https://shiptest.ga/stats/rounds/699)

## Testmerges:
[#816: 'Overmap Rework' by MarkSuckerberg at commit 2463f08e90](https://github.com/Shiptest-SS13/Shiptest/pull/816)
[#726: 'KapuLimbs v1.1: Update Icons Soft Refactor & Clockvox' by Kapu1178 at commit fc512ccb32](https://github.com/Shiptest-SS13/Shiptest/pull/726)
[#874: 'Bubble tweaks' by retlaw34 at commit 4d995d1ae8](https://github.com/Shiptest-SS13/Shiptest/pull/874)
[#852: 'Ruins for the Space Gods' by SweetBlueSylveon at commit cff85953c1](https://github.com/Shiptest-SS13/Shiptest/pull/852)
[#839: 'BYO-class' by triplezeta at commit 6e06554104](https://github.com/Shiptest-SS13/Shiptest/pull/839)
[#826: 'Pill trilogy: The sweet return of the successor unchained' by Dimasw99 at commit fb34162132](https://github.com/Shiptest-SS13/Shiptest/pull/826)
[#800: 'Chisels now work on all atoms that can be smoothed' by ZephyrTFA at commit b7440a813f](https://github.com/Shiptest-SS13/Shiptest/pull/800)
[#784: 'Hunting Revolver + .357 Rebalance' by Apogee-dev at commit 032e3065ef](https://github.com/Shiptest-SS13/Shiptest/pull/784)
[#778: 'Temporarily removes Hyena from purchase' by Apogee-dev at commit 21c6874360](https://github.com/Shiptest-SS13/Shiptest/pull/778)

## Reproduction:

Do *slap
![image](https://user-images.githubusercontent.com/58402542/155817569-4cd8906f-0e85-438c-b26e-bcd76ddd922a.png)

**Comment by Kapu1178** [comment]
Fixed
