### ISSUE TITLE
[FEATURE] moth hair

### ISSUE THREAD

**Issue by tiramisuapimancer** [shiptest-ss13/Shiptest#885]
### Additional Info:

It wouldn't be that hard to give moths the ability to have hair, the main thing stopping it being added ATM is that it'd be preferable to force the hair's color to be in the color of the moth's selected fluff, so someone would need to figure out some fresh and fancy way of tying specific color codes to specific fluffs and then having the moth's hair color set to that

**Comment by Sylphily** [comment]
Last time I checked it was rather hard to add hair because of the species system, but I might be wrong. Also why would moths need hair?

**Comment by Ms-Mee** [comment]
> Last time I checked it was rather hard to add hair because of the species system, but I might be wrong. Also why would moths need hair?

Not that difficult, and why would they not need hair?

**Comment by tiramisuapimancer** [comment]
Looks nice

**Comment by Martinpachu** [comment]
> > Last time I checked it was rather hard to add hair because of the species system, but I might be wrong. Also why would moths need hair?
> 
> Not that difficult, and why would they not need hair?

they can have wigs

**Comment by Martinpachu** [comment]
this IS wigmetagang propaganda

**Comment by Martinpachu** [comment]
joking aside,i dont know if hair would really fit moths,though if they matched fluff color and i saw some examples,maybe

**Comment by rye-rice** [comment]
![Screenshot_2549](https://user-images.githubusercontent.com/58402542/155898309-65039f42-eda9-45f4-82c2-18225e418230.png)
![Screenshot_2551](https://user-images.githubusercontent.com/58402542/155898311-c0015066-5b43-481c-a207-d8f22b6b687e.png)
Issue with moth hair is, well, mothpeople weren't made with hair in mind. You could probabaly pull off the look like how Loviar is doing in the above pictures, but I would assume most other hairstyles will have clipping issues

**Comment by tiramisuapimancer** [comment]
looks fine to me

**Comment by Martinpachu** [comment]
> ![Screenshot_2549](https://user-images.githubusercontent.com/58402542/155898309-65039f42-eda9-45f4-82c2-18225e418230.png) ![Screenshot_2551](https://user-images.githubusercontent.com/58402542/155898311-c0015066-5b43-481c-a207-d8f22b6b687e.png) Issue with moth hair is, well, mothpeople weren't made with hair in mind. You could probabaly pull off the look like how Loviar is doing in the above pictures, but I would assume most other hairstyles will have clipping issues

yeah,i'd have guessed there'd be problems with some hairstyles

**Comment by tiramisuapimancer** [comment]
I should probably elaborate, I mean that it *should* look like the hair and the neck-fluff are melded together, because the intent would be that they're the same overall thing
