### ISSUE TITLE
[BUG] Handheld Radios can be used by crit/dead and ghost players.

### ISSUE THREAD

**Issue by Lianvee** [shiptest-ss13/Shiptest#891]
As the title would explain, players that are in critical/dead can use handheld radio hotkeys to toggle speaker and broadcast on and off. Allowing them to call for help even if they're unable to use the item in question in their current state.
This also extends to ghosts, though can only toggle the speaker, and can even do this for a handheld radio found in a living player's inventory.

## Reproduction:
[Playing]
1. Be in critical or dead.

2. Use alt-click OR control-alt-click on a handheld radio in vicinity OR inventory to toggle broadcast and speaker.

3. If successful, a chat notice should pop up.

[Dead]
1. Find a handheld radio on the floor, or observe a player.

2. Use control-alt-lick to toggle it's speaker.

3. If successful, a chat notice should pop up.

**Comment by Ms-Mee** [comment]
See #806 for more information as to why
