### ISSUE TITLE
[BUG]SCRUBBERS STILL SCRUB WHILE OFF

### ISSUE THREAD

**Issue by PrefabQuasar** [shiptest-ss13/Shiptest#896]
## Round ID:
[713](https://shiptest.ga/stats/rounds/713)

## Testmerges:
Master commit: [383361c5aa975851248b3b1e3ffdb1a276f7a855](https://github.com/Shiptest-SS13/Shiptest/commit/383361c5aa975851248b3b1e3ffdb1a276f7a855)
The following pull requests are currently test merged:
[#882: 'Misc Fixes' by MarkSuckerberg at commit 2bb777f312](https://github.com/Shiptest-SS13/Shiptest/pull/882)
[#879: 'Fixes manifest bug' by MarkSuckerberg at commit d556dbec77](https://github.com/Shiptest-SS13/Shiptest/pull/879)
[#878: 'Midas-class Vault Ship' by Sparks3301 at commit 6a663f6905](https://github.com/Shiptest-SS13/Shiptest/pull/878)
[#877: 'Kicking around the runtime viewer, again' by MarkSuckerberg at commit 31aa236741](https://github.com/Shiptest-SS13/Shiptest/pull/877)
[#846: 'Arrowhead-class ' by TheNeoGamer42 at commit 958143e564](https://github.com/Shiptest-SS13/Shiptest/pull/846)
[#839: 'BYO-class' by triplezeta at commit 6e06554104](https://github.com/Shiptest-SS13/Shiptest/pull/839)
[#838: 'New jungleplanet ruin: Nest-1' by triplezeta at commit 19d0154634](https://github.com/Shiptest-SS13/Shiptest/pull/838)
[#778: 'Temporarily removes Hyena from purchase' by Apogee-dev at commit 21c6874360](https://github.com/Shiptest-SS13/Shiptest/pull/778)
[#726: 'KapuLimbs v1.1: Update Icons Soft Refactor & Clockvox' by Kapu1178 at commit 998384c78c](https://github.com/Shiptest-SS13/Shiptest/pull/726)

## Reproduction:
![image](https://user-images.githubusercontent.com/78622038/156905930-ddf58be0-a528-4a1a-bbd1-41b798117cc5.png)
place a scrubber, observe as the scrubber scrubs any gas its set to, without being on. how in the name of god did this happen.

**Comment by Ms-Mee** [comment]
I have no mouth and I must scrub

**Comment by Zevotech** [comment]
I have no ass and I must contaminate the air supply
