### ISSUE TITLE
[BUG] Undocks wait for planet deloads

### ISSUE THREAD

**Issue by PrefabQuasar** [shiptest-ss13/Shiptest#931]
## Testmerges:
not needed, this is caused by  Overmap Rework #816 

## Reproduction:
When a ship undocking from a planet would cause the planet to deload, the ship undocks, and then waits until the planet has fully(and slowly) finished deloading, before it removes the docking state and unlocks the helm console there's no reason that I can see for this to have been intentional, since ships that don't cause a deload don't need to wait like this.

**Comment by u-have-small-pp** [comment]
i think this was  a feature to reduce lag and load new planets
