### ISSUE TITLE
[BUG] Bluespace jump helm console dialog

### ISSUE THREAD

**Issue by PrefabQuasar** [shiptest-ss13/Shiptest#932]
## Testmerges:
not needed, this is caused by https://github.com/shiptest-ss13/Shiptest/pull/816

## Reproduction:
The "Bluespace Jump in progress. Controls suspended" dialog on helm consoles does not check if you are alive or not before speaking, and lacks a cooldown. Ghosts can spam the shit out of it.

**Comment by MarkSuckerberg** [comment]
Actually caused by initial implementation in #236, fixing
