### ISSUE TITLE
[BUG] Weather sometimes being contained to a ruin.

### ISSUE THREAD

**Issue by Zevotech** [shiptest-ss13/Shiptest#975]
## Round ID:
[796](https://shiptest.ga/stats/rounds/796)

![image](https://user-images.githubusercontent.com/95449138/163281377-f9dd6a3c-04ff-4076-ba8d-f26bce94d0fd.png)
![image](https://user-images.githubusercontent.com/95449138/163281438-067258d3-3e69-4475-95e8-bf4134bfa09e.png)

## Testmerges:
#726: 'KapuLimbs v1.1: Update Icons Soft Refactor & Clockvox' by Kapu1178 at commit 66650bc8bb](https://github.com/Shiptest-SS13/Shiptest/pull/726)
#671: 'Kepori Frying Code' by AsciiSquid at commit 7693542f7c](https://github.com/Shiptest-SS13/Shiptest/pull/671
#601: 'Overmap Expansion #3' by retlaw34 at commit d321954879](https://github.com/Shiptest-SS13/Shiptest/pull/601
#908: 'Maintains my maps' by SweetBlueSylveon at commit 41122f789d](https://github.com/Shiptest-SS13/Shiptest/pull/908
#890: 'Nemo-class Spacelife Research Vessel' by TypeVar at commit 9166937b8e](https://github.com/Shiptest-SS13/Shiptest/pull/890
#839: 'BYO-class' by triplezeta at commit 6e06554104](https://github.com/Shiptest-SS13/Shiptest/pull/839
#652: 'Weathers' by Azarak at commit 45bd1be9f4](https://github.com/Shiptest-SS13/Shiptest/pull/652

## Reproduction:
Unsure, occured late into the round and seems to have only been noticed by me.

**Comment by Azarak** [comment]
Weird, could be something due to the way map generation CHECK_TICKs. If I could debug this issue on the live server I'd probably have an answer

**Comment by Zevotech** [comment]
this bug is still around, very much a thing
