### ISSUE TITLE
Nagant Revolver Speedloaders holding less rounds than it should

### ISSUE THREAD

**Issue by Derpguy3** [shiptest-ss13/Shiptest#991]
Issue reported from  Round ID: [815](https://shiptest.ga/stats/rounds/815) (Shiptest)

Reporting client version: 514.1582

**Issue Description**
The Nagant revolver has capacity for 7 rounds, yet the speed loaders have only 6 rounds and are also limited to holding 6 rounds despite it having a sprite with a 7th round slot.

**Test Merges**
[#726: 'KapuLimbs v1.1: Update Icons Soft Refactor & Clockvox' by Kapu1178 at commit 31cda9909f](https://github.com/Shiptest-SS13/Shiptest/pull/726)
[#908: 'Maintains my maps' by SweetBlueSylveon at commit 41122f789d](https://github.com/Shiptest-SS13/Shiptest/pull/908)
[#839: 'BYO-class' by triplezeta at commit a38a383746](https://github.com/Shiptest-SS13/Shiptest/pull/839)
[#652: 'Weathers' by Azarak at commit 45bd1be9f4](https://github.com/Shiptest-SS13/Shiptest/pull/652)
[#943: 'Bay clicky noises 3: Zzzzzip' by retlaw34 at commit 44acf821f3](https://github.com/Shiptest-SS13/Shiptest/pull/943)
[#928: 'Resprites intercoms' by Quantum-M at commit c0a5c8740c](https://github.com/Shiptest-SS13/Shiptest/pull/928)
[#601: 'Overmap Expansion #3' by retlaw34 at commit f0aa926fe1](https://github.com/Shiptest-SS13/Shiptest/pull/601)
[#890: 'Nemo-class Spacelife Research Vessel' by TypeVar at commit beea8328c6](https://github.com/Shiptest-SS13/Shiptest/pull/890)
[#950: 'Adds cement and concrete, used to make concrete walls and floors.' by tmtmtl30 at commit 087cbe5d3d](https://github.com/Shiptest-SS13/Shiptest/pull/950)
[#967: 'Reworks the Carina to a Minuteman ship' by Apogee-dev at commit 7633980b93](https://github.com/Shiptest-SS13/Shiptest/pull/967)
[#957: 'High glass is no more' by PrefabQuasar at commit cdbe54b685](https://github.com/Shiptest-SS13/Shiptest/pull/957)
[#984: 'Fixes scrubbers scrubbing while off' by IndusRobot at commit ec17e1a573](https://github.com/Shiptest-SS13/Shiptest/pull/984)
[#985: 'Fixes some scrunches with loadout' by tiramisuapimancer at commit 80b50b1e8f](https://github.com/Shiptest-SS13/Shiptest/pull/985)
[#982: 'Schmiedeberg-class Pharmacology Ship' by TypeVar at commit ca62a08e20](https://github.com/Shiptest-SS13/Shiptest/pull/982)
[#986: 'Adds utility closets to sheetcrafting' by Recoherent at commit 06ef7f35b4](https://github.com/Shiptest-SS13/Shiptest/pull/986)

**Comment by Apogee-dev** [comment]
That's from #967, which added nagant loaders in the first place. Fixed in latest commit.

**Comment by Fikou** [comment]
solved
